import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

import { SCENARIO_NAMES } from "../lib/seed/scenarioNames.ts";

/**
 * SCENARIOS.md must describe the data that actually exists.
 *
 * The document is assembled from the manifests' own index, so the failure mode
 * is not "someone wrote it wrong" but "someone regenerated the corpus and did
 * not regenerate the document". That is exactly the drift that makes a record
 * map worse than no record map, so it is a test rather than a convention.
 */

const DOC = path.join(process.cwd(), "SCENARIOS.md");
const MANIFEST_DIR = path.join(process.cwd(), "fixtures", "creator_scenarios", "generated");

test("SCENARIOS.md exists and is generated, not hand-written", () => {
  assert.ok(fs.existsSync(DOC), "SCENARIOS.md is missing");
  const text = fs.readFileSync(DOC, "utf8");
  assert.match(text, /Generated by scripts\/generate-scenarios-doc\.mjs/);
});

test("SCENARIOS.md is current with the manifests", () => {
  // Regenerating and diffing is the only check that cannot be satisfied by
  // editing the document to match itself.
  execFileSync("node", ["scripts/generate-scenarios-doc.mjs", "--check"], {
    cwd: process.cwd(),
    stdio: "pipe",
  });
});

test("every scenario is documented, and every documented seed exists", () => {
  const text = fs.readFileSync(DOC, "utf8");
  for (const name of SCENARIO_NAMES) {
    assert.ok(text.includes(`\`${name}\``), `SCENARIOS.md never mentions ${name}`);
    assert.ok(
      fs.existsSync(path.join(MANIFEST_DIR, `${name}.json`)),
      `${name} is documented but has no manifest`
    );
  }
});

test("every record id in the document is a real record", () => {
  const text = fs.readFileSync(DOC, "utf8");
  const known = new Set();
  for (const name of SCENARIO_NAMES) {
    const data = JSON.parse(fs.readFileSync(path.join(MANIFEST_DIR, `${name}.json`), "utf8"));
    for (const rel of data.relationships ?? []) known.add(rel.id.slice(0, 8));
    for (const job of data.jobs ?? []) known.add(job.id.slice(0, 8));
  }
  // The document shortens ids for reading; each one still has to resolve.
  const referenced = [...text.matchAll(/\|\s*`([0-9a-f]{8})`\s*\|/g)].map((match) => match[1]);
  assert.ok(referenced.length > 0, "the document references no records at all");
  const missing = [...new Set(referenced)].filter((id) => !known.has(id));
  assert.deepEqual(missing, [], `documented ids that do not exist: ${missing.join(", ")}`);
});

test("every documented route is one the product actually serves", () => {
  const text = fs.readFileSync(DOC, "utf8");
  const routes = [...text.matchAll(/`(\/applications\?[^`]+)`/g)]
    .map((match) => match[1])
    // `seed=<name>` in the instructions is a placeholder showing the shape, not
    // a route to open.
    .filter((route) => !route.includes("<"));
  assert.ok(routes.length > 0, "the document names no routes");
  const problems = [];
  for (const route of routes) {
    const params = new URLSearchParams(route.split("?")[1]);
    const seed = params.get("seed");
    if (seed && !SCENARIO_NAMES.includes(seed)) problems.push(`${route} names unknown seed ${seed}`);
    const view = params.get("view");
    if (view && !["inbox", "pipeline"].includes(view)) problems.push(`${route} names unknown view`);
    // Sample data is opt-in: a documented sample route that omits it would send
    // someone to their real inbox and confuse them about what they are seeing.
    if (!params.has("demo")) problems.push(`${route} does not turn sample data on`);
  }
  assert.deepEqual(problems, [], `unusable documented routes:\n${problems.join("\n")}`);
});

test("the document makes no payment-custody claim", () => {
  const text = fs.readFileSync(DOC, "utf8");
  // The one place the words may appear is where the document states the
  // product does *not* do these things.
  const limitations = text.slice(text.indexOf("## Known limitations"));
  // QA instructions legitimately say "check the card does not claim funds are
  // held". Stripping the negated form first means this asserts on claims rather
  // than on the words, which is the difference between a check and a keyword ban.
  const body = text
    .slice(0, text.indexOf("## Known limitations"))
    .replace(/without (claiming|implying|asserting)[^|.]*/gi, "")
    .replace(/(does not|never|no) [^|.]*/gi, "");
  assert.doesNotMatch(body, /funds are (safe|secure|held)|escrow protects|money is held/i);
  assert.match(limitations, /No real payment processing/);
});

test("every required workflow has a findable example", () => {
  const text = fs.readFileSync(DOC, "utf8");
  const section = text.slice(text.indexOf("## Workflow index"), text.indexOf("## Coverage matrix"));
  assert.ok(section.length > 0, "the workflow index is missing");
  assert.doesNotMatch(
    section,
    /No indexed example/,
    "a required workflow has no example — the corpus does not cover it"
  );
  for (const workflow of [
    "New application",
    "Interview proposal",
    "Hire",
    "Payment funded",
    "Disputed",
    "Withdrawal",
    "Archived",
    "Star",
    "Snooze",
    "Send failure",
    "Broken thumbnail",
    "Retired job",
    "Empty state",
  ]) {
    assert.ok(section.includes(workflow), `the workflow index omits "${workflow}"`);
  }
});
