"""Provider replies generated by mutating ground truth, field by field.

Eighteen hand-built variance cases proved the shapes somebody thought of. A model
does not produce the shapes somebody thought of — it omits a field one run and
phrases it differently the next, and the combination that matters is usually two
fields going wrong at once, because that is where two independently-correct
fallbacks disagree.

So this starts from a page whose facts are known and generates replies by
applying one behaviour per field: correct, omitted, null, empty, whitespace,
reworded, contradicting the page, malformed, overlong, an unknown enum. Pairwise
across fields rather than the full Cartesian product, which would be millions of
cases proving the same thing.

Every assertion is about the *final native draft*, never the reply. What a page
states explicitly must survive every one of these, because the page is the
evidence and the reply is only one reading of it.
"""

from __future__ import annotations

import itertools
import random

import pytest

from app.core.job_import_labelled_fields import labelled_facts
from app.core.job_import_native_values import convert_to_native
from app.db.seed_data_job_import_labelled import labelled_pay_page

#: What the page itself says, independent of any reply.
GROUND_TRUTH = {
    "budget_amount": 5000,
    "budget_currency": "INR",
    "budget_unit": "per month",
    "engagement_type": "ongoing_freelance",
}

#: One reply's behaviour for one field.
BEHAVIOURS = (
    "correct",
    "omitted",
    "null",
    "empty",
    "whitespace",
    "reworded",
    "contradicting",
    "malformed",
    "overlong",
    "unknown_enum",
    "duplicated",
)

FIELDS = (
    "title",
    "engagement_type",
    "work_mode",
    "location",
    "experience_level",
    "responsibilities",
    "tools",
)

SEEDS = (20260808, 11, 23, 57, 101, 777, 4242)


def _value_for(field: str, behaviour: str, rng: random.Random):
    """What a reply would carry for one field under one behaviour."""

    correct = {
        "title": "(Paid) Content Creator & Social Media Manager",
        "engagement_type": "internship",  # faithful to the page's stale markup
        "work_mode": "remote",
        "location": "Bengaluru, Karnataka, IN",
        "experience_level": "At least 2 years",
        "responsibilities": ["Edit Reels.", "Write captions.", "Report weekly."],
        "tools": ["CapCut", "InShot"],
    }[field]

    if behaviour == "correct":
        return correct
    if behaviour == "omitted":
        return ...
    if behaviour == "null":
        return None
    if behaviour == "empty":
        return [] if isinstance(correct, list) else ""
    if behaviour == "whitespace":
        return ["   "] if isinstance(correct, list) else "   "
    if behaviour == "reworded":
        if isinstance(correct, list):
            return [item.upper() for item in correct]
        return str(correct).upper()
    if behaviour == "contradicting":
        return {
            "title": "Senior Backend Engineer",
            "engagement_type": "full_time",
            "work_mode": "onsite",
            "location": "Mumbai, Maharashtra, IN",
            "experience_level": "10-12 years",
            "responsibilities": ["Maintain Kubernetes clusters."],
            "tools": ["Kubernetes"],
        }[field]
    if behaviour == "malformed":
        return {"unexpected": "object"} if not isinstance(correct, list) else [{"a": 1}]
    if behaviour == "overlong":
        return ["x" * 5000] if isinstance(correct, list) else "x" * 5000
    if behaviour == "unknown_enum":
        return ["not_a_value"] if isinstance(correct, list) else "not_a_value"
    if behaviour == "duplicated":
        return correct + correct if isinstance(correct, list) else f"{correct} {correct}"
    raise AssertionError(behaviour)


def _pairwise_cases(limit: int) -> list[dict[str, str]]:
    """Every pair of (field, behaviour) values covered at least once.

    Pairwise rather than Cartesian: 7 fields × 11 behaviours is 19 million
    combinations that would prove nothing 19 million times. Every *pair* of
    field behaviours appearing together is where independent fallbacks collide.
    """

    required = {
        (left, left_behaviour, right, right_behaviour)
        for left, right in itertools.combinations(FIELDS, 2)
        for left_behaviour in BEHAVIOURS
        for right_behaviour in BEHAVIOURS
    }
    cases: list[dict[str, str]] = []
    rng = random.Random(20260808)
    while required and len(cases) < limit:
        case = {field: rng.choice(BEHAVIOURS) for field in FIELDS}
        covered = {
            (left, case[left], right, case[right])
            for left, right in itertools.combinations(FIELDS, 2)
        }
        if covered & required:
            required -= covered
            cases.append(case)
    # Top up with fresh random draws so the corpus is large as well as covering.
    for seed in SEEDS:
        seeded = random.Random(seed)
        while len(cases) < limit:
            cases.append({field: seeded.choice(BEHAVIOURS) for field in FIELDS})
    return cases[:limit]


CASES = _pairwise_cases(5000)
PAGE_TEXT, PAGE_METADATA = labelled_pay_page()
PAGE_FACTS = labelled_facts(PAGE_TEXT)


class TestTheGeneratedCorpusIsWorthTrusting:
    def test_enough_cases_and_full_pairwise_coverage(self) -> None:
        assert len(CASES) >= 5000, len(CASES)

        covered = {
            (left, case[left], right, case[right])
            for case in CASES
            for left, right in itertools.combinations(FIELDS, 2)
        }
        required = {
            (left, left_behaviour, right, right_behaviour)
            for left, right in itertools.combinations(FIELDS, 2)
            for left_behaviour in BEHAVIOURS
            for right_behaviour in BEHAVIOURS
        }

        assert required <= covered, len(required - covered)

    def test_every_behaviour_is_exercised_for_every_field(self) -> None:
        for field in FIELDS:
            behaviours = {case[field] for case in CASES}
            assert behaviours == set(BEHAVIOURS), (field, set(BEHAVIOURS) - behaviours)


class TestThePagesOwnFactsSurviveEveryReply:
    """The central property: the page is the evidence, the reply is a reading."""

    def test_the_labelled_rate_is_independent_of_anything_a_reply_says(self) -> None:
        # Read once, asserted against every case: the labelled reader never
        # consults the reply, so no combination of reply behaviours can move it.
        assert PAGE_FACTS.budget_amount == GROUND_TRUTH["budget_amount"]
        assert PAGE_FACTS.budget_currency == GROUND_TRUTH["budget_currency"]
        assert PAGE_FACTS.budget_unit == GROUND_TRUTH["budget_unit"]

    def test_the_labelled_engagement_is_independent_too(self) -> None:
        assert PAGE_FACTS.engagement_type == GROUND_TRUTH["engagement_type"]

    @pytest.mark.parametrize("chunk", range(10))
    def test_no_generated_reply_produces_an_invalid_native_value(
        self, chunk: int
    ) -> None:
        """Whatever a reply carries, nothing invalid may reach the draft."""

        rng = random.Random(20260808 + chunk)
        for case in CASES[chunk::10]:
            for field, behaviour in case.items():
                value = _value_for(field, behaviour, rng)
                if value is ...:
                    continue
                conversion = convert_to_native(field, value)

                if conversion.outcome not in ("exact", "broadened"):
                    # Refusing is always safe.
                    continue

                stored = conversion.native_value
                # An accepted value must be usable. Whitespace, malformed
                # objects and unknown enums reaching the draft as facts is the
                # class this catches.
                assert stored is None or not (
                    isinstance(stored, str) and stored and not stored.strip()
                ), f"{field}/{behaviour} stored whitespace: {stored!r}"
                assert not isinstance(stored, dict), (
                    f"{field}/{behaviour} stored an object: {stored!r}"
                )
                # And one level down: a bullet list of objects renders as
                # `{'a': 1}` to a candidate just as surely.
                if isinstance(stored, list):
                    assert not any(
                        isinstance(entry, (dict, list)) for entry in stored
                    ), f"{field}/{behaviour} stored structures: {stored!r}"

    @pytest.mark.parametrize("chunk", range(10))
    def test_no_generated_reply_narrows_experience(self, chunk: int) -> None:
        rng = random.Random(31337 + chunk)
        for case in CASES[chunk::10]:
            value = _value_for("experience_level", case["experience_level"], rng)
            if value is ... or not isinstance(value, str):
                continue
            conversion = convert_to_native("experience_level", value)
            stored = str(conversion.native_value or "")

            # Whatever the reply said, the stored value may only contain
            # numbers the reply itself contained.
            source_numbers = {char for char in value if char.isdigit()}
            for char in stored:
                if char.isdigit():
                    assert char in source_numbers, f"{value!r} -> {stored!r}"


class TestOneBadFieldDoesNotEraseTheOthers:
    @pytest.mark.parametrize("broken", FIELDS)
    def test_a_single_corrupt_field_leaves_the_rest_convertible(
        self, broken: str
    ) -> None:
        rng = random.Random(4242)
        for behaviour in ("malformed", "unknown_enum", "overlong", "whitespace"):
            for field in FIELDS:
                value = _value_for(
                    field, behaviour if field == broken else "correct", rng
                )
                if value is ...:
                    continue
                conversion = convert_to_native(field, value)

                if field != broken:
                    # Unrelated fields must still convert. Collateral loss —
                    # one bad field taking the whole reply with it — is the
                    # failure this guards.
                    assert conversion.outcome in ("exact", "broadened"), (
                        f"{field} lost because {broken} was {behaviour}"
                    )


class TestProviderContradictionNeverBeatsThePage:
    @pytest.mark.parametrize("behaviour", BEHAVIOURS)
    def test_the_rate_the_page_printed_is_unaffected(self, behaviour: str) -> None:
        # The reply has no compensation field at all in this corpus, which is
        # faithful: the real page's markup carried none. Whatever else the
        # reply does, the labelled row is what supplies the rate.
        assert labelled_facts(PAGE_TEXT).budget_amount == 5000

    def test_a_contradicting_engagement_does_not_change_the_labelled_one(self) -> None:
        # The reply says internship, faithfully echoing the page's stale
        # markup. The employer's own labelled row says freelance and wins.
        assert labelled_facts(PAGE_TEXT).engagement_type == "ongoing_freelance"


class TestMetamorphicReplyTransformations:
    """Transformations that must not change what a recruiter finally sees."""

    @pytest.mark.parametrize(
        ("left", "right"),
        [
            ("correct", "reworded"),
            ("correct", "duplicated"),
        ],
    )
    def test_equivalent_or_noisier_wording_converts_the_same_or_is_refused(
        self, left: str, right: str
    ) -> None:
        rng = random.Random(7)
        for field in ("work_mode", "engagement_type"):
            first = convert_to_native(field, _value_for(field, left, rng))
            second = convert_to_native(field, _value_for(field, right, rng))

            # Case is normalisation, so uppercase must convert identically.
            # Duplication is noise, so it may be refused — but it must never
            # convert to a *different* supported value.
            assert second.native_value in (first.native_value, None), (
                f"{field}: {left}={first.native_value!r} {right}={second.native_value!r}"
            )

    def test_reordering_a_list_does_not_change_its_contents(self) -> None:
        rng = random.Random(9)
        original = _value_for("responsibilities", "correct", rng)
        reordered = list(reversed(original))

        first = convert_to_native("responsibilities", original)
        second = convert_to_native("responsibilities", reordered)

        assert sorted(first.native_value or []) == sorted(second.native_value or [])
