"""Facts an employer prints under a label, when the markup is silent or wrong.

A live import produced a draft with no pay and an engagement of "internship" for
a paid freelance brief. Neither was a reasoning failure: the page's syndicated
JSON-LD carried no compensation at all and declared ``employmentType: INTERN``,
while the employer's own copy said

    Compensation   ₹5,000 / mo
    Type           Part-time / Freelance

Reading the markup faithfully therefore meant asking the recruiter how pay was
measured about a page that had answered exactly that.

Markup is generated by whoever syndicated the listing; the labelled copy is
written by the employer about their own job. So the label fills what the markup
omits, and wins where the two disagree.

The fixtures below keep the *shape* — a label, a value, a contradiction — and
none of the employers who happened to expose it.
"""

from __future__ import annotations

import pytest

from app.core.job_import_labelled_fields import labelled_facts

PAGE = """
(Paid) Content Creator & Social Media Manager
Structured employment type: INTERN
Compensation ₹5,000 / mo
Type Part-time / Freelance
Location Remote-friendly
"""


class TestTheLabelIsReadWhenMarkupIsSilent:
    def test_a_stated_monthly_figure_becomes_compensation(self) -> None:
        facts = labelled_facts(PAGE)

        assert facts.budget_amount == 5000
        assert facts.budget_currency == "INR"
        assert facts.budget_unit == "per month"
        # One figure is a fixed rate. Inventing a second bound would advertise a
        # spread the employer never offered.
        assert facts.compensation_mode == "fixed"

    @pytest.mark.parametrize(
        ("line", "amount", "currency", "unit"),
        [
            ("Compensation $30 per hour", 30, "USD", "per hour"),
            ("Salary INR 40000 monthly", 40000, "INR", "per month"),
            ("Pay £250 / day", 250, "GBP", "per day"),
            ("Budget €1,500 per project", 1500, "EUR", "per project"),
            ("Stipend ₹8,000/mo", 8000, "INR", "per month"),
        ],
    )
    def test_common_unit_forms_are_understood(
        self, line: str, amount: int, currency: str, unit: str
    ) -> None:
        facts = labelled_facts(line)

        assert (facts.budget_amount, facts.budget_currency, facts.budget_unit) == (
            amount,
            currency,
            unit,
        )


class TestNothingIsInvented:
    @pytest.mark.parametrize(
        "line",
        [
            "Compensation Competitive",
            "Salary Depends on experience",
            "Pay 5000",  # no currency and no period: not a rate
            "Compensation ₹5,000",  # a figure with no period
            "Budget To be discussed",
        ],
    )
    def test_an_unclear_figure_yields_nothing(self, line: str) -> None:
        facts = labelled_facts(line)

        assert facts.budget_amount is None
        assert facts.compensation_mode is None

    def test_an_empty_page_yields_nothing(self) -> None:
        assert labelled_facts("").budget_amount is None
        assert labelled_facts(None).engagement_type is None


class TestEngagementComesFromTheEmployersOwnWords:
    def test_part_time_freelance_is_never_an_internship(self) -> None:
        # The exact regression: markup said INTERN, the employer said otherwise.
        assert labelled_facts(PAGE).engagement_type != "internship"

    @pytest.mark.parametrize(
        ("line", "expected"),
        [
            ("Type Part-time / Freelance", "ongoing_freelance"),
            ("Type Full-time", "full_time"),
            ("Job Type Contract", "fixed_term"),
            ("Employment type Part time", "part_time"),
            ("Type Retainer", "retainer"),
            # A page that really does offer an internship still says so.
            ("Type Internship", "internship"),
        ],
    )
    def test_each_stated_type_maps_to_a_supported_engagement(
        self, line: str, expected: str
    ) -> None:
        assert labelled_facts(line).engagement_type == expected

    def test_an_unrecognised_type_is_left_alone(self) -> None:
        assert labelled_facts("Type Something unusual").engagement_type is None


class TestEvidenceIsKept:
    def test_each_value_records_the_line_it_came_from(self) -> None:
        evidence = labelled_facts(PAGE).evidence or {}

        assert evidence["compensation"] == "₹5,000 / mo"
        assert evidence["engagement_type"] == "Part-time / Freelance"


class TestLabelledFactsBeatLowerAuthorityMetadata:
    """The precedence, pinned where it actually broke.

    The rule existed but never ran for conflict rows: those are constructed
    without a review_status key, so a guard comparing against "pending" saw None
    and skipped them. Whether a labelled fact won came down to whether the
    provider happened to produce a conflict on that run — two of three live runs
    asked the recruiter about a fact the page stated plainly.
    """

    @staticmethod
    def _may_fill(**overrides) -> bool:
        from app.services.job_import_service import JobImportService

        existing = {
            "field_path": "engagement_type",
            "provenance_state": "conflicting_source_values",
            "proposed_value": None,
        }
        existing.update(overrides)
        return JobImportService._structured_value_may_fill(existing)

    def test_an_unset_review_status_counts_as_untouched(self) -> None:
        # The actual mechanism lives in the merge loop, which reaches its
        # precedence path only when the general fill rule declines. What broke
        # was the status comparison there: conflict rows carry no review_status,
        # so `== "pending"` was False and the labelled fact never applied.
        import inspect

        from app.services.job_import_service import JobImportService

        source = inspect.getsource(JobImportService._merge_structured_page_signals)
        assert 'existing.get("review_status") in (None, "", "pending")' in source
        assert "employer_labelled" in source
        # And a genuine conflict is still only bypassed for labelled fields.
        assert "labelled_paths" in source

    def test_a_recruiter_reviewed_row_is_still_protected(self) -> None:
        for status in ("accepted", "edited", "rejected"):
            assert not self._may_fill(
                review_status=status, proposed_value="internship"
            ), status

    def test_a_usable_settled_reading_is_still_protected(self) -> None:
        assert not self._may_fill(
            provenance_state="extracted_from_source",
            proposed_value="full_time",
            review_status="pending",
        )


class TestPartTimeFreelanceIsFreelance:
    """Two compatible descriptors are not a question.

    "Part-time / Freelance" names how the engagement is structured and how much
    of it there is. The product's engagement field holds the structure —
    freelance — and weekly hours carry the volume, so nothing is lost and there
    is nothing to ask.
    """

    def test_the_structure_wins_over_the_volume(self) -> None:
        assert labelled_facts("Type Part-time / Freelance").engagement_type == (
            "ongoing_freelance"
        )

    @pytest.mark.parametrize(
        ("line", "expected"),
        [
            ("Type Freelance / Part-time", "ongoing_freelance"),
            ("Type Part-time", "part_time"),
            ("Type Freelance", "ongoing_freelance"),
            ("Type Full-time contract", "fixed_term"),
        ],
    )
    def test_compatible_pairs_resolve_without_asking(
        self, line: str, expected: str
    ) -> None:
        assert labelled_facts(line).engagement_type == expected
