// lib/jobs.ts

import { Job, StartTimeframe } from "./types";

export const CATEGORIES = [
  "All",
  "Editing",
  "Design",
  "Writing",
  "Thumbnails",
  "Shorts",
  "Motion Graphics",
  "Channel Manager",
  "Research",
  "Voice Over",
  "Marketing",
] as const;

export const START_TIME_VALUES: StartTimeframe[] = ["ASAP", "<1mo", "<2mo", "<3mo", "Flexible"];

const toSlug = (value: string) =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const RAW_JOBS: Job[] = [
  {
    id: "1",
    title: "Video editor for YouTube (long-form, retention-focused)",
    category: "Editing",
    budget: "₹350–₹3,500 per project",
    experience: "1–3 years",
    location: "Remote",
    postedShort: "5h",
    views: 355,
    applicants: 12,
    responseRate: 82,
    channel: {
      name: "Finance Channel",
      logoUrl: "https://picsum.photos/seed/finance/96/96",
      subscribers: 128000,
      verified: true,
    },
    tags: ["Premiere", "Story pace", "SFX", "Captions", "Sound cleanup"],
    startTimeframe: "<1mo",
    type: "One-time",
    referenceVideos: [
      { title: "Pacing + retention reference", url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },
      { title: "Clean captions + sound style", url: "https://www.youtube.com/watch?v=3JZ_D3ELwOQ" },
      { title: "Structure + story flow reference", url: "https://www.youtube.com/watch?v=9bZkp7q19f0" },
    ],
    channelProfileSlug: "finance-creator",
    channelExternalUrl: "https://www.youtube.com/@financecreator",
    postedByAgency: true,
    agencyProfileSlug: "example-agency",
    managedByAgencyName: "Example Creator Agency",
  },
  {
    id: "2",
    title: "Thumbnail designer (CTR-focused, 2–3 concepts)",
    category: "Thumbnails",
    budget: "₹600–₹1,200 per month",
    experience: "0–2 years",
    location: "Remote",
    postedShort: "1d",
    views: 92,
    applicants: 4,
    responseRate: 60,
    channel: {
      name: "Tech Channel",
      logoUrl: "https://picsum.photos/seed/tech/96/96",
      subscribers: 54000,
      verified: false,
    },
    tags: ["Photoshop", "Bold type", "A/B ideas", "Fast iterations"],
    startTimeframe: "ASAP",
    type: "Part-time",
    referenceVideos: [
      { title: "High CTR packaging reference", url: "https://www.youtube.com/watch?v=kJQP7kiw5Fk" },
      { title: "Bold type + contrast reference", url: "https://www.youtube.com/watch?v=uelHwf8o7_U" },
    ],
    channelProfileSlug: "tech-channel",
    channelExternalUrl: "https://www.youtube.com/@techchannel",
    postedByAgency: true,
    agencyProfileSlug: "northstar-creator-agency",
    managedByAgencyName: "Northstar Creator Agency",
  },
  {
    id: "3",
    title: "Script writer for Hindi explainers (8–10 mins)",
    category: "Writing",
    budget: "₹150–₹400 per project",
    experience: "1–3 years",
    location: "Remote",
    postedShort: "8h",
    views: 210,
    applicants: 18,
    responseRate: 74,
    channel: {
      name: "Edu Hindi",
      logoUrl: "https://picsum.photos/seed/edu/96/96",
      subscribers: 312000,
      verified: true,
    },
    tags: ["Hooks", "Research", "Hindi", "Tone match", "Fast delivery"],
    startTimeframe: "Flexible",
    type: "One-time",
    referenceVideos: [
      { title: "Explainer structure reference", url: "https://www.youtube.com/watch?v=fLexgOxsZu0" },
      { title: "Hook + pacing reference", url: "https://www.youtube.com/watch?v=RgKAFK5djSk" },
    ],
    channelProfileSlug: "edu-hindi",
    channelExternalUrl: "https://www.youtube.com/@eduhindi",
  },
  {
    id: "4",
    title: "Shorts editor for daily YouTube Shorts (fast paced, captions)",
    category: "Shorts",
    budget: "₹800–₹1,600 per month",
    experience: "0–1 years",
    location: "Remote",
    postedShort: "2h",
    views: 680,
    applicants: 22,
    responseRate: 71,
    channel: {
      name: "Motivation Shorts",
      logoUrl: "https://picsum.photos/seed/motivation/96/96",
      subscribers: 980000,
      verified: true,
    },
    tags: ["CapCut", "Subtitles", "Beat sync", "Fast turnaround"],
    startTimeframe: "<2mo",
    type: "Monthly",
    referenceVideos: [
      { title: "Fast captions + rhythm reference", url: "https://www.youtube.com/watch?v=OPf0YbXqDm0" },
      { title: "Shorts pacing reference", url: "https://www.youtube.com/watch?v=2Vv-BfVoq4g" },
      { title: "Beat sync reference", url: "https://www.youtube.com/watch?v=JGwWNGJdvx8" },
    ],
  },
  {
    id: "5",
    title: "Motion graphics: animated callouts + kinetic text for videos",
    category: "Motion Graphics",
    budget: "₹250–₹800 per project",
    experience: "1–3 years",
    location: "Remote",
    postedShort: "12h",
    views: 140,
    applicants: 7,
    responseRate: 64,
    channel: {
      name: "Science Visuals",
      logoUrl: "https://picsum.photos/seed/science/96/96",
      subscribers: 210000,
      verified: true,
    },
    tags: ["After Effects", "Kinetic type", "Templates", "Callouts"],
    startTimeframe: "<3mo",
    type: "One-time",
    referenceVideos: [
      { title: "Callouts + lower thirds reference", url: "https://www.youtube.com/watch?v=oRdxUFDoQe0" },
      { title: "Kinetic text reference", url: "https://www.youtube.com/watch?v=YQHsXMglC9A" },
    ],
  },
  {
    id: "6",
    title: "Channel manager to run uploads, analytics, and team coordination",
    category: "Channel Manager",
    budget: "₹1,200–₹2,800 per month",
    experience: "3–5 years",
    location: "Remote",
    postedShort: "2d",
    views: 310,
    applicants: 15,
    responseRate: 55,
    channel: {
      name: "Startup Stories",
      logoUrl: "https://picsum.photos/seed/startup/96/96",
      subscribers: 76000,
      verified: false,
    },
    tags: ["Notion", "Content calendar", "YouTube Studio", "Ops"],
    startTimeframe: "<1mo",
    type: "Part-time",
    referenceVideos: [
      { title: "Ops workflow reference", url: "https://www.youtube.com/watch?v=Zi_XLOBDo_Y" },
      { title: "Upload cadence reference", url: "https://www.youtube.com/watch?v=60ItHLz5WEA" },
    ],
  },
  {
    id: "7",
    title: "Research assistant for documentary-style videos (sources + outline)",
    category: "Research",
    budget: "₹100–₹250 per project",
    experience: "1–3 years",
    location: "Remote",
    postedShort: "1d",
    views: 520,
    applicants: 31,
    responseRate: 78,
    channel: {
      name: "History Deep Dives",
      logoUrl: "https://picsum.photos/seed/history/96/96",
      subscribers: 430000,
      verified: true,
    },
    tags: ["Primary sources", "Fact check", "Outline", "Citations"],
    startTimeframe: "ASAP",
    type: "One-time",
    referenceVideos: [
      { title: "Doc-style structure reference", url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },
      { title: "Narrative pacing reference", url: "https://www.youtube.com/watch?v=3JZ_D3ELwOQ" },
      { title: "Visual + research tone reference", url: "https://www.youtube.com/watch?v=9bZkp7q19f0" },
    ],
  },
  {
    id: "8",
    title: "Graphic designer for channel branding (banner, icons, templates)",
    category: "Design",
    budget: "₹300–₹900 per project",
    experience: "0–2 years",
    location: "Remote",
    postedShort: "6h",
    views: 175,
    applicants: 9,
    responseRate: 69,
    channel: {
      name: "Indie Gamer",
      logoUrl: "https://picsum.photos/seed/gaming/96/96",
      subscribers: 22000,
      verified: false,
    },
    tags: ["Figma", "Brand kit", "YouTube banner", "Templates"],
    startTimeframe: "Flexible",
    type: "One-time",
    referenceVideos: [
      { title: "Brand kit reference", url: "https://www.youtube.com/watch?v=ktvTqknDobU" },
      { title: "Channel banner style reference", url: "https://www.youtube.com/watch?v=450p7goxZqg" },
    ],
  },
  {
    id: "9",
    title: "Voice-over artist (English, warm tone) for finance videos",
    category: "Voice Over",
    budget: "₹80–₹200 per project",
    experience: "Any",
    location: "Remote",
    postedShort: "9h",
    views: 205,
    applicants: 14,
    responseRate: 62,
    channel: {
      name: "Money & Mindset",
      logoUrl: "https://picsum.photos/seed/money/96/96",
      subscribers: 64000,
      verified: false,
    },
    tags: ["Neutral accent", "Clean audio", "Fast delivery", "Consistency"],
    startTimeframe: "<2mo",
    type: "One-time",
    referenceVideos: [
      { title: "Warm VO tone reference", url: "https://www.youtube.com/watch?v=UceaB4D0jpo" },
      { title: "Clean narration reference", url: "https://www.youtube.com/watch?v=F57P9C4SAW4" },
    ],
  },
  {
    id: "10",
    title: "Marketing specialist to grow newsletter + YouTube",
    category: "Marketing",
    budget: "₹800–₹2,000 per month",
    experience: "1–3 years",
    location: "Remote",
    postedShort: "3d",
    views: 260,
    applicants: 11,
    responseRate: 73,
    channel: {
      name: "Content Business",
      logoUrl: "https://picsum.photos/seed/business/96/96",
      subscribers: 118000,
      verified: true,
    },
    tags: ["Distribution", "Hooks", "SEO basics", "Email marketing"],
    startTimeframe: "<1mo",
    type: "Part-time",
    referenceVideos: [
      { title: "Growth strategy reference", url: "https://www.youtube.com/watch?v=SlPhMPnQ58k" },
      { title: "Newsletter + video growth reference", url: "https://www.youtube.com/watch?v=J---aiyznGQ" },
    ],
  },
  {
    id: "11",
    title: "Editing: podcast → YouTube multi-cam cut (1 episode/week)",
    category: "Editing",
    budget: "₹200–₹600 per project",
    experience: "1–3 years",
    location: "Remote",
    postedShort: "1d",
    views: 410,
    applicants: 19,
    responseRate: 66,
    channel: {
      name: "The Long Talk",
      logoUrl: "https://picsum.photos/seed/podcast/96/96",
      subscribers: 92000,
      verified: false,
    },
    tags: ["Multicam", "Audio cleanup", "Chapters", "Snappy pacing"],
    startTimeframe: "<3mo",
    type: "Monthly",
    referenceVideos: [
      { title: "Multicam pacing reference", url: "https://www.youtube.com/watch?v=hT_nvWreIhg" },
      { title: "Podcast-to-YouTube style reference", url: "https://www.youtube.com/watch?v=YykjpeuMNEk" },
    ],
  },
  {
    id: "12",
    title: "Thumbnail designer for gaming channel (high-contrast, bold)",
    category: "Thumbnails",
    budget: "₹400–₹1,000 per month",
    experience: "0–2 years",
    location: "Remote",
    postedShort: "4h",
    views: 330,
    applicants: 8,
    responseRate: 70,
    channel: {
      name: "Console Chaos",
      logoUrl: "https://picsum.photos/seed/console/96/96",
      subscribers: 410000,
      verified: true,
    },
    tags: ["Photoshop", "High contrast", "Fast variants", "Packaging"],
    startTimeframe: "ASAP",
    type: "Monthly",
    referenceVideos: [
      { title: "Gaming packaging reference", url: "https://www.youtube.com/watch?v=YQHsXMglC9A" },
      { title: "High contrast thumb reference", url: "https://www.youtube.com/watch?v=OPf0YbXqDm0" },
    ],
  },
  {
    id: "13",
    title: "Shorts editor (3/day) for fitness content creator (trend-aware)",
    category: "Shorts",
    budget: "₹900–₹2,000 per month",
    experience: "0–1 years",
    location: "Remote",
    postedShort: "7h",
    views: 760,
    applicants: 27,
    responseRate: 68,
    channel: {
      name: "Fit in 60",
      logoUrl: "https://picsum.photos/seed/fitness/96/96",
      subscribers: 250000,
      verified: true,
    },
    tags: ["Captions", "Beat cuts", "Trend pacing", "CapCut/PR"],
    startTimeframe: "<2mo",
    type: "Monthly",
    referenceVideos: [
      { title: "Fitness shorts pacing reference", url: "https://www.youtube.com/watch?v=2Vv-BfVoq4g" },
      { title: "Trend pacing reference", url: "https://www.youtube.com/watch?v=JGwWNGJdvx8" },
    ],
  },
  {
    id: "14",
    title: "Script writer for tech reviews (structured, clear, punchy)",
    category: "Writing",
    budget: "₹120–₹300 per project",
    experience: "1–3 years",
    location: "Remote",
    postedShort: "2d",
    views: 190,
    applicants: 16,
    responseRate: 59,
    channel: {
      name: "Gadget Minute",
      logoUrl: "https://picsum.photos/seed/gadgets/96/96",
      subscribers: 88000,
      verified: false,
    },
    tags: ["Clarity", "Outline", "Hooks", "Fast revisions"],
    startTimeframe: "Flexible",
    type: "One-time",
    referenceVideos: [
      { title: "Tech review structure reference", url: "https://www.youtube.com/watch?v=kJQP7kiw5Fk" },
      { title: "Punchy writing reference", url: "https://www.youtube.com/watch?v=uelHwf8o7_U" },
    ],
  },
  {
    id: "15",
    title: "Designer for explainer diagrams + simple motion overlays",
    category: "Design",
    budget: "₹250–₹700 per project",
    experience: "0–2 years",
    location: "Remote",
    postedShort: "10h",
    views: 0,
    applicants: 6,
    responseRate: 0,
    channel: {
      name: "Learn Visually",
      logoUrl: "https://picsum.photos/seed/visual/96/96",
      subscribers: 56000,
      verified: false,
    },
    tags: ["Figma", "Clean layout", "Minimal style", "Consistency"],
    startTimeframe: "<1mo",
    type: "One-time",
    referenceVideos: [
      { title: "Diagram clarity reference", url: "https://www.youtube.com/watch?v=fLexgOxsZu0" },
      { title: "Minimal motion reference", url: "https://www.youtube.com/watch?v=RgKAFK5djSk" },
    ],
  },
  {
    id: "16",
    title: "Motion graphics pack: lower thirds + subscribe + transitions",
    category: "Motion Graphics",
    budget: "₹500–₹1,500 per project",
    experience: "3–5 years",
    location: "Remote",
    postedShort: "3d",
    views: 220,
    applicants: 10,
    responseRate: 58,
    channel: {
      name: "Cinematic Cuts",
      logoUrl: "https://picsum.photos/seed/cinema/96/96",
      subscribers: 140000,
      verified: true,
    },
    tags: ["After Effects", "Templates", "Reusable", "Brand match"],
    startTimeframe: "ASAP",
    type: "One-time",
    referenceVideos: [
      { title: "Lower thirds reference", url: "https://www.youtube.com/watch?v=oRdxUFDoQe0" },
      { title: "Transition pack reference", url: "https://www.youtube.com/watch?v=SlPhMPnQ58k" },
    ],
  },
  {
    id: "17",
    title: "Researcher for finance stories (sources, claims, counterpoints)",
    category: "Research",
    budget: "₹150–₹350 per project",
    experience: "1–3 years",
    location: "Remote",
    postedShort: "1d",
    views: 410,
    applicants: 13,
    responseRate: 77,
    channel: {
      name: "Finance Explained",
      logoUrl: "https://picsum.photos/seed/finexp/96/96",
      subscribers: 205000,
      verified: true,
    },
    tags: ["Sources", "Fact check", "Structured notes", "Neutral"],
    startTimeframe: "<3mo",
    type: "One-time",
    referenceVideos: [
      { title: "Finance storytelling reference", url: "https://www.youtube.com/watch?v=UceaB4D0jpo" },
      { title: "Claims + counterpoints reference", url: "https://www.youtube.com/watch?v=F57P9C4SAW4" },
    ],
  },
  {
    id: "18",
    title: "Channel manager for consistent uploads + sponsor coordination",
    category: "Channel Manager",
    budget: "₹1,500–₹3,500 per month",
    experience: "5+ years",
    location: "Remote",
    postedShort: "5d",
    views: 280,
    applicants: 9,
    responseRate: 61,
    channel: {
      name: "Big Content Ops",
      logoUrl: "https://picsum.photos/seed/ops/96/96",
      subscribers: 620000,
      verified: true,
    },
    tags: ["Ops", "Sponsors", "Publishing", "Analytics"],
    startTimeframe: "<2mo",
    type: "Part-time",
    referenceVideos: [
      { title: "Sponsor ops reference", url: "https://www.youtube.com/watch?v=Zi_XLOBDo_Y" },
      { title: "Publishing system reference", url: "https://www.youtube.com/watch?v=60ItHLz5WEA" },
    ],
  },
];

const defaultAbout = (job: Job) =>
  `${job.channel.name} is looking for help on ${job.category.toLowerCase()} work. ` +
  `We care about clarity, pacing, and a consistent voice across every upload.`;

const defaultResponsibilities =
  "Define deliverables for week 1\nShare progress updates\nIterate fast on feedback";

const defaultRequirements =
  "Relevant experience in the role\nStrong communication\nReliable turnaround";

const defaultHowToApply =
  "Share a short intro, 2–3 relevant examples, your tools, and availability.";

export const JOBS: Job[] = RAW_JOBS.map((job) => ({
  ...job,
  about: job.about?.trim() ? job.about : defaultAbout(job),
  responsibilities: job.responsibilities?.trim() ? job.responsibilities : defaultResponsibilities,
  requirements: job.requirements?.trim() ? job.requirements : defaultRequirements,
  howToApply: job.howToApply?.trim() ? job.howToApply : defaultHowToApply,
  channelProfileSlug: job.channelProfileSlug || toSlug(job.channel.name) || undefined,
  channelExternalUrl: job.channelExternalUrl || undefined,
  postedByAgency: Boolean(job.postedByAgency),
  agencyProfileSlug: job.agencyProfileSlug || undefined,
}));
