import { Job } from "./types";

export type AppliedJob = Job & {
  applicationStatus: "Applied";
  appliedAt: string;
};

export type ReceivedApplicant = {
  id: string;
  name: string;
  username: string;
  headline: string;
  bio: string;
  skills: string[];
  tools: string[];
  portfolioLinks: Array<{ label: string; url: string }>;
  rating: number;
  reviewCount: number;
  appliedAt: string;
  jobAppliedToId: string;
  jobAppliedToTitle: string;
  location: string;
  availability: string;
};

export const appliedJobs: AppliedJob[] = [
  {
    id: "applied-01",
    title: "Long-form editor for weekly founder stories",
    category: "Editing",
    budget: "₹55,000-₹1,00,000 per episode",
    experience: "2-4 years",
    location: "Remote (US hours overlap)",
    postedShort: "3d",
    views: 286,
    applicants: 34,
    responseRate: 74,
    channel: {
      name: "Build In Public Daily",
      logoUrl: "https://picsum.photos/seed/buildpublicdaily/96/96",
      subscribers: 184000,
      verified: true,
    },
    tags: ["Premiere Pro", "Story pacing", "Sound design", "Retention"],
    startTimeframe: "ASAP",
    type: "Part-time",
    platform: "YouTube",
    applicationStatus: "Applied",
    appliedAt: "2d ago",
  },
  {
    id: "applied-02",
    title: "Thumbnail designer for finance explainers",
    category: "Thumbnails",
    budget: "₹80,000-₹1,30,000 per month",
    experience: "1-3 years",
    location: "Remote",
    postedShort: "1d",
    views: 194,
    applicants: 21,
    responseRate: 67,
    channel: {
      name: "Finance Clarity",
      logoUrl: "https://picsum.photos/seed/financeclarity/96/96",
      subscribers: 91000,
      verified: true,
    },
    tags: ["Photoshop", "CTR testing", "Packaging", "A/B concepts"],
    startTimeframe: "<1mo",
    type: "Monthly",
    platform: "YouTube",
    applicationStatus: "Applied",
    appliedAt: "1d ago",
  },
  {
    id: "applied-03",
    title: "Shorts editor for daily productivity clips",
    category: "Shorts",
    budget: "₹3,000-₹6,500 per short",
    experience: "1-2 years",
    location: "Remote",
    postedShort: "5h",
    views: 412,
    applicants: 47,
    responseRate: 81,
    channel: {
      name: "Atomic Workflow",
      logoUrl: "https://picsum.photos/seed/atomicworkflow/96/96",
      subscribers: 263000,
      verified: true,
    },
    tags: ["CapCut", "Motion captions", "Hook-first", "Fast turnaround"],
    startTimeframe: "ASAP",
    type: "One-time",
    platform: "YouTube",
    applicationStatus: "Applied",
    appliedAt: "4h ago",
  },
  {
    id: "applied-04",
    title: "Research assistant for documentary scripts",
    category: "Research",
    budget: "₹20,000-₹40,000 per script",
    experience: "1-3 years",
    location: "Remote",
    postedShort: "2d",
    views: 167,
    applicants: 19,
    responseRate: 62,
    channel: {
      name: "History in Motion",
      logoUrl: "https://picsum.photos/seed/historyinmotion/96/96",
      subscribers: 520000,
      verified: true,
    },
    tags: ["Fact-checking", "Primary sources", "Outlines", "Citations"],
    startTimeframe: "<2mo",
    type: "One-time",
    platform: "YouTube",
    applicationStatus: "Applied",
    appliedAt: "2d ago",
  },
  {
    id: "applied-05",
    title: "Motion graphics editor for tutorial overlays",
    category: "Motion Graphics",
    budget: "₹40,000-₹75,000 per project",
    experience: "2-5 years",
    location: "Remote",
    postedShort: "9h",
    views: 241,
    applicants: 16,
    responseRate: 58,
    channel: {
      name: "Design Sprint Lab",
      logoUrl: "https://picsum.photos/seed/designsprintlab/96/96",
      subscribers: 67000,
      verified: false,
    },
    tags: ["After Effects", "Kinetic text", "Callouts", "Template systems"],
    startTimeframe: "Flexible",
    type: "One-time",
    platform: "YouTube",
    applicationStatus: "Applied",
    appliedAt: "7h ago",
  },
  {
    id: "applied-06",
    title: "Channel manager for weekly publishing ops",
    category: "Channel Manager",
    budget: "₹1,50,000-₹2,00,000 per month",
    experience: "3-5 years",
    location: "Remote (EU-friendly)",
    postedShort: "3d",
    views: 136,
    applicants: 12,
    responseRate: 64,
    channel: {
      name: "Scale Stories",
      logoUrl: "https://picsum.photos/seed/scalestories/96/96",
      subscribers: 48000,
      verified: false,
    },
    tags: ["Notion", "Upload QA", "YouTube Studio", "Weekly planning"],
    startTimeframe: "<1mo",
    type: "Part-time",
    platform: "YouTube",
    applicationStatus: "Applied",
    appliedAt: "3d ago",
  },
  {
    id: "applied-07",
    title: "Script writer for marketing + growth videos",
    category: "Writing",
    budget: "₹25,000-₹60,000 per video",
    experience: "2-4 years",
    location: "Remote",
    postedShort: "12h",
    views: 208,
    applicants: 27,
    responseRate: 72,
    channel: {
      name: "Growth Craft",
      logoUrl: "https://picsum.photos/seed/growthcraft/96/96",
      subscribers: 145000,
      verified: true,
    },
    tags: ["Hooks", "Narrative arcs", "B2B tone", "Research"],
    startTimeframe: "<1mo",
    type: "One-time",
    platform: "YouTube",
    applicationStatus: "Applied",
    appliedAt: "10h ago",
  },
  {
    id: "applied-08",
    title: "Instagram reels editor for content creator brand clips",
    category: "Shorts",
    budget: "₹1,00,000-₹1,60,000 per month",
    experience: "1-3 years",
    location: "Remote",
    postedShort: "18h",
    views: 329,
    applicants: 41,
    responseRate: 79,
    channel: {
      name: "Creator Growth Studio",
      logoUrl: "https://picsum.photos/seed/creatorgrowthstudio/96/96",
      subscribers: 73000,
      verified: true,
    },
    tags: ["Reels pacing", "Caption design", "Trend adaption", "Batch edits"],
    startTimeframe: "ASAP",
    type: "Monthly",
    platform: "Instagram",
    applicationStatus: "Applied",
    appliedAt: "14h ago",
  },
];

export const receivedApplicants: ReceivedApplicant[] = [
  {
    id: "recv-01",
    name: "Maya Chen",
    username: "mayaedits",
    headline: "Short-form editor focused on retention pacing and hooks",
    bio: "I edit daily shorts and reels for education and content creator business channels. Fast turnaround, clean captions, and strong first-three-second pacing.",
    skills: ["Short-form editing", "Story pacing", "Caption timing", "Audio polish"],
    tools: ["Premiere Pro", "After Effects", "CapCut"],
    portfolioLinks: [
      { label: "Short-form reel", url: "https://portfolio.example.com/maya/reel" },
      { label: "Retention cuts", url: "https://portfolio.example.com/maya/retention" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "2h ago",
    jobAppliedToId: "posted-101",
    jobAppliedToTitle: "YouTube Shorts editor for daily uploads",
    location: "Toronto, Canada",
    availability: "Can start this week",
  },
  {
    id: "recv-02",
    name: "Arjun Rao",
    username: "arjuncuts",
    headline: "Editor for long-form educational content",
    bio: "I specialize in multi-cam interviews, story structuring, and pacing for 8-15 minute content creator videos.",
    skills: ["Long-form editing", "Interview cleanup", "Color correction"],
    tools: ["Premiere Pro", "DaVinci Resolve", "Audition"],
    portfolioLinks: [
      { label: "Interview sample", url: "https://portfolio.example.com/arjun/interview" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "4h ago",
    jobAppliedToId: "posted-101",
    jobAppliedToTitle: "YouTube Shorts editor for daily uploads",
    location: "Bengaluru, India",
    availability: "Available evenings IST",
  },
  {
    id: "recv-03",
    name: "Lena Brooks",
    username: "lenathumbs",
    headline: "CTR-focused thumbnail designer for business channels",
    bio: "I design high-contrast thumbnails with fast A/B concept iterations and packaging systems.",
    skills: ["Thumbnail design", "CTR packaging", "A/B testing"],
    tools: ["Photoshop", "Figma", "Midjourney"],
    portfolioLinks: [
      { label: "Thumbnail gallery", url: "https://portfolio.example.com/lena/thumbs" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "5h ago",
    jobAppliedToId: "posted-102",
    jobAppliedToTitle: "Thumbnail designer for finance explainers",
    location: "Austin, USA",
    availability: "Immediate",
  },
  {
    id: "recv-04",
    name: "Noah Kim",
    username: "noahvisuals",
    headline: "Designer for thumbnails and content creator brand systems",
    bio: "I build reusable thumbnail templates and visual systems tuned for clarity at mobile size.",
    skills: ["Visual hierarchy", "Template systems", "Brand consistency"],
    tools: ["Photoshop", "Illustrator", "Figma"],
    portfolioLinks: [
      { label: "Template pack", url: "https://portfolio.example.com/noah/templates" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "7h ago",
    jobAppliedToId: "posted-102",
    jobAppliedToTitle: "Thumbnail designer for finance explainers",
    location: "Seoul, South Korea",
    availability: "10-15 hrs/week",
  },
  {
    id: "recv-05",
    name: "Priya Nair",
    username: "priyanair",
    headline: "Research assistant for documentary and explainer scripts",
    bio: "I gather and verify sources, draft outlines, and maintain references for creator-led documentaries.",
    skills: ["Research", "Fact-checking", "Source synthesis"],
    tools: ["Notion", "Google Scholar", "Airtable"],
    portfolioLinks: [
      { label: "Research sample", url: "https://portfolio.example.com/priya/research" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "9h ago",
    jobAppliedToId: "posted-103",
    jobAppliedToTitle: "Research + script assistant for deep dives",
    location: "Chennai, India",
    availability: "Weekday mornings IST",
  },
  {
    id: "recv-06",
    name: "Jonas Reed",
    username: "jonaswrites",
    headline: "Script strategist for educational YouTube content",
    bio: "I support script structure, citations, and audience retention arcs for content creator channels.",
    skills: ["Script structure", "Narrative flow", "Research notes"],
    tools: ["Notion", "Google Docs", "Perplexity"],
    portfolioLinks: [
      { label: "Script excerpts", url: "https://portfolio.example.com/jonas/scripts" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "11h ago",
    jobAppliedToId: "posted-103",
    jobAppliedToTitle: "Research + script assistant for deep dives",
    location: "Berlin, Germany",
    availability: "Flexible CET",
  },
  {
    id: "recv-07",
    name: "Ava Mitchell",
    username: "avacreative",
    headline: "Content editor with shorts + long-form crossover experience",
    bio: "I blend short-form pacing with long-form narrative clarity to improve session duration and retention.",
    skills: ["Retention edits", "Narrative cuts", "Caption design"],
    tools: ["Premiere Pro", "After Effects", "Photoshop"],
    portfolioLinks: [
      { label: "Content reel", url: "https://portfolio.example.com/ava/reel" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "12h ago",
    jobAppliedToId: "posted-101",
    jobAppliedToTitle: "YouTube Shorts editor for daily uploads",
    location: "London, UK",
    availability: "20 hrs/week",
  },
  {
    id: "recv-08",
    name: "Diego Alvarez",
    username: "diegothumbs",
    headline: "Thumbnail designer for finance and productivity niches",
    bio: "I focus on clean hierarchy, expressive faces, and high-contrast topic framing.",
    skills: ["CTR optimization", "Visual packaging", "Concept iteration"],
    tools: ["Photoshop", "Lightroom", "Figma"],
    portfolioLinks: [
      { label: "Finance examples", url: "https://portfolio.example.com/diego/finance" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "14h ago",
    jobAppliedToId: "posted-102",
    jobAppliedToTitle: "Thumbnail designer for finance explainers",
    location: "Madrid, Spain",
    availability: "Immediate",
  },
  {
    id: "recv-09",
    name: "Hana Park",
    username: "hanastory",
    headline: "Research + story development for deep-dive channels",
    bio: "I structure research into clear outlines with verified citations and production-ready notes.",
    skills: ["Historical research", "Outline writing", "Citation systems"],
    tools: ["Notion", "Roam", "Google Scholar"],
    portfolioLinks: [
      { label: "Deep-dive packet", url: "https://portfolio.example.com/hana/deepdive" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "16h ago",
    jobAppliedToId: "posted-103",
    jobAppliedToTitle: "Research + script assistant for deep dives",
    location: "Vancouver, Canada",
    availability: "Open this month",
  },
  {
    id: "recv-10",
    name: "Ethan Cole",
    username: "ethancuts",
    headline: "High-tempo shorts editor for content creator education brands",
    bio: "I edit daily short-form pipelines with strong hook pacing and conversion-focused endings.",
    skills: ["Shorts edits", "Beat sync", "Fast revisions"],
    tools: ["Premiere Pro", "CapCut", "Descript"],
    portfolioLinks: [
      { label: "Shorts montage", url: "https://portfolio.example.com/ethan/shorts" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "18h ago",
    jobAppliedToId: "posted-101",
    jobAppliedToTitle: "YouTube Shorts editor for daily uploads",
    location: "Chicago, USA",
    availability: "Mon-Fri",
  },
  {
    id: "recv-11",
    name: "Sofia Malik",
    username: "sofiavisual",
    headline: "Thumbnail specialist for conversion-driven content",
    bio: "I design thumbnail systems optimized for repeatable workflows and clear visual hierarchy.",
    skills: ["Thumbnail systems", "Design QA", "Style guides"],
    tools: ["Figma", "Photoshop", "Canva Pro"],
    portfolioLinks: [
      { label: "Channel packaging", url: "https://portfolio.example.com/sofia/packaging" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "20h ago",
    jobAppliedToId: "posted-102",
    jobAppliedToTitle: "Thumbnail designer for finance explainers",
    location: "Dubai, UAE",
    availability: "15 hrs/week",
  },
  {
    id: "recv-12",
    name: "Ravi Menon",
    username: "raviresearch",
    headline: "Research producer for educational content creator channels",
    bio: "I compile fact-checked research briefs and source-backed script notes for weekly publishing calendars.",
    skills: ["Research briefs", "Fact validation", "Outline planning"],
    tools: ["Notion", "Airtable", "Google Docs"],
    portfolioLinks: [
      { label: "Research brief sample", url: "https://portfolio.example.com/ravi/brief" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "22h ago",
    jobAppliedToId: "posted-103",
    jobAppliedToTitle: "Research + script assistant for deep dives",
    location: "Mumbai, India",
    availability: "Can start in 3 days",
  },
  {
    id: "recv-13",
    name: "Tessa Gray",
    username: "tessashorts",
    headline: "Editor for faceless shorts channels",
    bio: "I create high-retention short edits with templates for titles, subtitles, and transitions.",
    skills: ["Template editing", "Subtitle workflows", "Retention pacing"],
    tools: ["CapCut", "Premiere Pro", "After Effects"],
    portfolioLinks: [
      { label: "Faceless shorts reel", url: "https://portfolio.example.com/tessa/faceless" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "1d ago",
    jobAppliedToId: "posted-101",
    jobAppliedToTitle: "YouTube Shorts editor for daily uploads",
    location: "Sydney, Australia",
    availability: "Part-time",
  },
  {
    id: "recv-14",
    name: "Marcus Lee",
    username: "marcusdesign",
    headline: "Packaging designer for creator-led education brands",
    bio: "I design thumbnails and supporting social assets with an emphasis on repeatable weekly production.",
    skills: ["Thumbnail design", "Visual strategy", "Batch workflows"],
    tools: ["Photoshop", "Illustrator", "Figma"],
    portfolioLinks: [
      { label: "Thumbnail case study", url: "https://portfolio.example.com/marcus/case-study" },
    ],
    rating: 0,
    reviewCount: 0,
    appliedAt: "1d ago",
    jobAppliedToId: "posted-102",
    jobAppliedToTitle: "Thumbnail designer for finance explainers",
    location: "Los Angeles, USA",
    availability: "Immediate",
  },
];
