"""sync models after auth/channel changes

Revision ID: 77462c28c80d
Revises: 0002_auth_channel_verification
Create Date: 2026-02-16 06:34:19.623305

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '77462c28c80d'
down_revision: str | None = '0002_auth_channel_verification'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('email_verification_tokens_token_key'), 'email_verification_tokens', type_='unique')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('youtube_channels_channel_id_key'), 'youtube_channels', type_='unique')
    op.drop_index(op.f('ix_youtube_channels_channel_id'), table_name='youtube_channels')
    op.create_index(op.f('ix_youtube_channels_channel_id'), 'youtube_channels', ['channel_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_channels_channel_id'), table_name='youtube_channels')
    op.create_index(op.f('ix_youtube_channels_channel_id'), 'youtube_channels', ['channel_id'], unique=False)
    op.create_unique_constraint(op.f('youtube_channels_channel_id_key'), 'youtube_channels', ['channel_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=False)
    op.create_unique_constraint(op.f('email_verification_tokens_token_key'), 'email_verification_tokens', ['token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
