/**
 * Demo interaction fixtures for Mock mode.
 *
 * Moved verbatim out of `lib/ownerInteractions.ts`, which had grown to hold the
 * public interaction types, the backend mapper, the display-label projection,
 * the time formatter *and* twelve hundred lines of fixture. Keeping sample data
 * in the same module as the code that ships is how the two datasets drifted
 * apart in the first place.
 *
 * This module is the **frontend seed boundary**: nothing here is production
 * code, and nothing here may be imported by a module that ships to users
 * outside the development/mock data-source boundary.
 *
 * Behaviour-preserving move. The records, their order, and every field are
 * unchanged; the canonical generator replaces them in a later commit.
 */

import type {
  InteractionTalentSnapshot,
  OwnerInteraction,
} from "../ownerInteractions";

/**
 * Seed-time anchor for this transitional fixture.
 *
 * Every record's age is expressed as an offset from one instant rather than as
 * a hand-typed label, which is what let the same column show `6 Jan 2026`,
 * `6d ago` and `1m ago` at once. Anchored at module load so the demo data never
 * goes stale, and so the ages a reviewer sees match the ages that were written.
 *
 * The canonical generator replaces this file; until then it must still be right.
 */
const SEED_ANCHOR = Date.now();

/** An ISO instant `seconds` before the anchor. */
const ago = (seconds: number): string =>
  new Date(SEED_ANCHOR - seconds * 1000).toISOString();


/**
 * The viewer's own talent listing, shown as the context card for every received
 * hiring request (a recruiter is interested in this listing). One listing is
 * reused across the demo requests, matching their shared sourceListingTitle.
 */
const OWN_TALENT_LISTING_SNAPSHOT: InteractionTalentSnapshot = {
  profileSlug: "demo-owner",
  name: "Your listing",
  headline: "Retention-focused long-form and shorts editing",
  rate: "₹2,000–₹3,500 per video",
  experience: "Less than 1 year",
  location: "Remote",
  availability: "Available · 2 retainer slots",
  tools: ["Premiere Pro", "After Effects"],
  niches: ["Finance", "Education", "Shorts"],
  experienceNote: "4 yrs editing for creator-led finance and education channels",
  portfolioHighlights: [],
  isOwnListing: true,
};

export const MOCK_OWNER_INTERACTIONS: OwnerInteraction[] = [
  // ---- Talent mode: applications this user sent to jobs ----
  {
    id: "t-app-sent-1",
    mode: "talent",
    direction: "sent",
    kind: "application",
    status: "pending",
    title: "Video editor for YouTube (long-form, retention-focused)",
    counterpartyName: "Finance Channel",
    counterpartyAvatarUrl: "https://picsum.photos/seed/finance/96/96",
    createdAt: ago(7200),
    updatedAt: ago(7200),
    message:
      "Hi — I edit long-form finance and education videos with a focus on retention pacing. I rebuilt the structure for two explainer channels last quarter and can match your captions and sound style from the references. Happy to do a paid test edit on one of your recent uploads.",
    firstMessageAnswers: {
      expected_rate: { amount: "2,800", unit: "per project" },
      relevant_portfolio: [
        {
          id: "t-app-sent-1-portfolio-1",
          title: "Retention edit — Finance explainer",
          url: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
          type: "Long-form edit",
          platform: "YouTube",
          description:
            "Edited a 14-minute personal-finance explainer: hook rewrite, pacing restructure, captions, B-roll, and final export.",
          role: "End-to-end edit, caption pass, sound cleanup",
          metrics: ["42% average retention lift", "1.8M views", "Edited end-to-end"],
          tags: ["Retention", "Finance", "YouTube"],
          tools: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
          timestampNotes: [
            { time: "0:00", seconds: 0, title: "Rewritten hook", description: "New cold-open that reframes the question in the first 8 seconds." },
            { time: "3:42", seconds: 222, title: "Pacing restructure", description: "Cut two minutes of setup and tightened the middle third." },
            { time: "9:15", seconds: 555, title: "B-roll + callouts", description: "Motion callouts over the data section for retention." },
          ],
        },
        {
          id: "t-app-sent-1-portfolio-2",
          title: "Captions + sound style reel",
          url: "https://portfolio.example.com/reels/caption-sound-style",
          type: "Shorts reel",
          platform: "Instagram",
          description:
            "A compilation of caption-heavy short-form edits with music ducking and punch-in timing.",
          role: "Caption design, sound design",
          tags: ["Captions", "Sound design"],
          tools: ["Premiere Pro", "CapCut"],
        },
        {
          id: "t-app-sent-1-portfolio-3",
          title: "Education series — 8-video pack",
          url: "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
          type: "Channel package",
          platform: "YouTube",
          description:
            "Full-season edit for a beginner-investing series with a repeatable template and consistent lower-thirds.",
          role: "Series lead editor",
          metrics: ["8-video series", "Delivered in 6 weeks"],
          tags: ["Education", "Explainer"],
          tools: ["Premiere Pro", "After Effects"],
          timestampNotes: [
            { time: "0:05", seconds: 5, title: "Series intro template", description: "Reusable animated intro built once and re-timed per episode." },
            { time: "6:30", seconds: 390, title: "Lower-thirds system", description: "Consistent lower-thirds and chapter cards across the pack." },
          ],
        },
      ],
      turnaround: { value: "3", unit: "days" },
      working_hours: "Evenings IST",
      relevant_experience: "2 finance explainers and 1 education series edited end to end last quarter.",
      tools_workflow: ["Premiere Pro", "After Effects", "Frame.io"],
      start_availability: "Within 1 week",
      fit_note: "I already edit finance and education videos with a retention-first workflow.",
      custom_instruction: {
        prompt: "Share one similar explainer you worked on and what you personally handled.",
        response: "I handled the pacing restructure, caption pass, sound cleanup, and final upload-ready export.",
        links: ["https://www.youtube.com/watch?v=jNQXAC9IVRw"],
      },
    },
    attachments: [
      { label: "Retention edit — Finance explainer", url: "https://www.youtube.com/watch?v=jNQXAC9IVRw" },
      { label: "Captions + sound style reel", url: "https://portfolio.example.com/reels/caption-sound-style" },
    ],
    job: {
      jobId: "1",
      title: "Video editor for YouTube (long-form, retention-focused)",
      channelName: "Finance Channel",
      channelLogoUrl: "https://picsum.photos/seed/finance/96/96",
      channelProfileSlug: "finance-creator",
      budget: "₹350–₹3,500 per project",
      workMode: "One-time · Remote",
      location: "Remote",
      experience: "1–3 years",
      tags: ["Premiere", "Story pace", "SFX", "Captions"],
listingStatus: "Open",
      creator: {
        platforms: ["youtube"],
        formats: ["Long-form video"],
        niches: ["Finance", "Education"],
        turnaround: { value: 3, unit: "calendar_days", basis: "first_draft" },
        compensation: { mode: "range", minimum: 350, maximum: 3500, currency: "INR", unit: "per project" },
        channelHandle: "finance-channel",
        employerKind: "creator",
        subscribers: 412000,
        cadence: "2 videos/week",
      },
    },
    timeline: [{ id: "t-app-sent-1-applied", label: "Application sent", occurredAt: ago(7200) }],
  },
  {
    id: "t-app-sent-2",
    mode: "talent",
    direction: "sent",
    kind: "application",
    status: "responded",
    title: "Shorts editor for daily YouTube Shorts (fast paced, captions)",
    counterpartyName: "Motivation Shorts",
    counterpartyAvatarUrl: "https://picsum.photos/seed/motivation/96/96",
    createdAt: ago(259200),
    updatedAt: ago(18000),
    unread: true,
    message:
      "I can run a daily shorts pipeline and keep your caption style consistent across editors.",
    firstMessageAnswers: {
      expected_rate: { amount: "1,200", unit: "per month" },
      turnaround: { value: "24", unit: "hours" },
      working_hours: "Mornings IST",
      relevant_experience: "Daily shorts pipeline for two faceless channels.",
      tools_workflow: ["CapCut", "Premiere Pro"],
      start_availability: "Immediately",
      fit_note: "I can run a daily shorts pipeline and keep your caption style consistent across editors.",
    },
    attachments: [{ label: "Shorts pacing reel", url: "https://portfolio.example.com/sample/shorts-reel" }],
    response: {
      from: "Motivation Shorts",
      body: "Your pacing reel is close to what we want. Can you start with a one-week trial batch of 5 shorts using next week's scripts?",
      sentAt: ago(18000),
    },
    replies: [
      {
        from: "You",
        body: "Happy to. I can pull next week's scripts from the shared drive and deliver the first batch of 5 within three days, captions in your house style.",
        sentAt: ago(14400),
      },
      {
        from: "Motivation Shorts",
        body: "Perfect. What's your availability for a 15-minute kickoff call this week to walk through the caption presets?",
        sentAt: ago(10800),
      },
    ],
    job: {
      jobId: "4",
      title: "Shorts editor for daily YouTube Shorts (fast paced, captions)",
      channelName: "Motivation Shorts",
      channelLogoUrl: "https://picsum.photos/seed/motivation/96/96",
      channelProfileSlug: "motivation-shorts",
      budget: "₹800–₹1,600 per month",
      workMode: "Monthly · Remote",
      location: "Remote",
      experience: "1–2 years",
      tags: ["CapCut", "Captions", "Beat sync", "Hooks"],
listingStatus: "Open",
      creator: {
        platforms: ["youtube"],
        formats: ["Shorts/Reels"],
        niches: ["Fitness", "Comedy"],
        turnaround: { value: 12, unit: "hours", basis: "final_delivery" },
        compensation: { mode: "fixed", minimum: 1400, currency: "INR", unit: "per month" },
        channelHandle: "motivationshorts",
        employerKind: "creator",
        subscribers: 96000,
        cadence: "5 shorts/week",
      },
    },
    timeline: [
      { id: "t-app-sent-2-applied", label: "Application sent", occurredAt: ago(259200) },
      { id: "t-app-sent-2-viewed", label: "Viewed by Motivation Shorts", occurredAt: ago(172800) },
      { id: "t-app-sent-2-responded", label: "Response received", occurredAt: ago(18000) },
    ],
  },
  {
    id: "t-app-sent-3",
    mode: "talent",
    direction: "sent",
    kind: "application",
    status: "declined",
    archivedAt: "2026-05-22T09:00:00.000Z",
    title: "Thumbnail designer (CTR-focused, 2–3 concepts)",
    counterpartyName: "Tech Channel",
    counterpartyAvatarUrl: "https://picsum.photos/seed/tech/96/96",
    createdAt: ago(604800),
    updatedAt: ago(345600),
    message:
      "I design high-contrast thumbnail concepts with fast iteration — usually 3 directions within 24 hours. Sharing a packaging set I did for a hardware review channel in a similar niche.",
    proposedTerms: "₹900 per month · 8 thumbnails",
    response: {
      from: "Tech Channel",
      body: "Thanks for the samples — your work is strong. We went with someone who had more long-form documentary packaging experience for this batch. We'll keep your profile for the next round.",
      sentAt: ago(345600),
    },
    job: {
      jobId: "2",
      title: "Thumbnail designer (CTR-focused, 2–3 concepts)",
      channelName: "Tech Channel",
      channelLogoUrl: "https://picsum.photos/seed/tech/96/96",
      channelProfileSlug: "tech-channel",
      budget: "₹600–₹1,200 per month",
      workMode: "Monthly · Remote",
      location: "Remote",
      experience: "1–3 years",
      tags: ["Photoshop", "CTR", "Packaging"],
listingStatus: "Open",
      creator: {
        platforms: ["youtube"],
        formats: ["Thumbnails"],
        niches: ["Technology"],
        turnaround: { value: 2, unit: "business_days", basis: "per_deliverable" },
        compensation: { mode: "fixed", minimum: 25, currency: "USD", unit: "per hour" },
        channelHandle: "tech-channel",
        employerKind: "agency",
        subscribers: 1300000,
        cadence: "3 videos/week",
      },
    },
    timeline: [
      { id: "t-app-sent-3-applied", label: "Application sent", occurredAt: ago(604800) },
      { id: "t-app-sent-3-viewed", label: "Viewed by Tech Channel", occurredAt: ago(518400) },
      { id: "t-app-sent-3-declined", label: "Declined by Tech Channel", occurredAt: ago(345600) },
    ],
  },
  {
    id: "t-app-sent-4",
    mode: "talent",
    direction: "sent",
    kind: "application",
    status: "viewed",
    title: "Script writer for Hindi explainers (8–10 mins)",
    counterpartyName: "Gyaan Express",
    counterpartyAvatarUrl: "https://picsum.photos/seed/gyaan/96/96",
    createdAt: ago(172800),
    updatedAt: ago(86400),
    message:
      "I write Hindi explainer scripts with a clear hook, simple analogies, and a tight 8–10 minute structure. I can match your conversational tone and include on-screen cue notes for the editor.",
    firstMessageAnswers: {
      relevant_experience: "Wrote 18 Hindi explainers across education and current-affairs channels.",
      start_availability: "Within 2 weeks",
      custom_instruction: {
        prompt: "Share a tight opening hook for a phone review video.",
        response:
          "Most phone reviews answer specs. I would open by showing the one everyday moment where the phone either saves you time or annoys you immediately.",
        links: [],
      },
    },
    job: {
      jobId: "5",
      title: "Script writer for Hindi explainers (8–10 mins)",
      channelName: "Gyaan Express",
      channelLogoUrl: "https://picsum.photos/seed/gyaan/96/96",
      channelProfileSlug: "gyaan-express",
      budget: "₹1,200–₹2,000 per script",
      workMode: "Monthly · Remote",
      location: "Remote",
      experience: "1–3 years",
      tags: ["Hindi", "Scripts", "Explainers", "Hooks"],
listingStatus: "Open",
      creator: {
        platforms: ["youtube"],
        formats: ["Scripts"],
        niches: ["Education"],
        turnaround: { value: 1, unit: "weeks", basis: "first_draft" },
        compensation: { unit: "commission", note: "10% of sponsorship revenue on scripts you write." },
        channelHandle: "gyaan-express",
        employerKind: "creator",
        subscribers: 228000,
        cadence: "1 video/week",
      },
    },
    timeline: [
      { id: "t-app-sent-4-applied", label: "Application sent", occurredAt: ago(172800) },
      { id: "t-app-sent-4-viewed", label: "Viewed by Gyaan Express", occurredAt: ago(86400) },
    ],
  },
  {
    id: "t-app-sent-5",
    mode: "talent",
    direction: "sent",
    kind: "application",
    status: "shortlisted",
    title: "Long-form editor for documentary-style finance deep dives",
    counterpartyName: "Moneywise India",
    counterpartyAvatarUrl: "https://picsum.photos/seed/moneywise/96/96",
    createdAt: ago(518400),
    updatedAt: ago(86400),
    unread: true,
    message:
      "I edit documentary-style finance videos — narrative pacing, archival overlays, and clean sound design. I've linked two deep dives I cut end to end and can adapt to your reference style.",
    firstMessageAnswers: {
      expected_rate: { amount: "3,500", unit: "per video" },
      relevant_portfolio: [
        {
          id: "t-app-sent-5-portfolio-1",
          title: "Deep dive — market crash explainer",
          url: "https://portfolio.example.com/docs/market-crash-deep-dive",
          type: "Documentary edit",
          platform: "YouTube",
          description:
            "22-minute documentary-style breakdown with archival overlays, narration timing, and layered sound design.",
          role: "Narrative edit, archival research, sound design",
          metrics: ["Avg view duration 11:04", "94% of runtime is original edit"],
          tags: ["Documentary", "Finance", "Sound design"],
        },
        {
          id: "t-app-sent-5-portfolio-2",
          title: "Deep dive — startup story",
          url: "https://portfolio.example.com/docs/startup-story",
          type: "Documentary edit",
          platform: "YouTube",
          description: "Founder-story cut with interview weaving, B-roll pacing, and a cold-open hook.",
          role: "Lead editor",
          tags: ["Documentary", "Retention"],
        },
      ],
      turnaround: { value: "5", unit: "days" },
      tools_workflow: ["Premiere Pro", "After Effects", "Audition"],
      fit_note: "Your documentary-style finance brief matches the pacing and archival work I already do.",
    },
    attachments: [
      { label: "Deep dive — market crash explainer", url: "https://portfolio.example.com/docs/market-crash-deep-dive" },
      { label: "Deep dive — startup story", url: "https://portfolio.example.com/docs/startup-story" },
    ],
    response: {
      from: "Moneywise India",
      body: "We liked your explainers work and shortlisted you. Can you share two more samples with heavier archival/B-roll use?",
      sentAt: ago(86400),
    },
    job: {
      jobId: "6",
      title: "Long-form editor for documentary-style finance deep dives",
      channelName: "Moneywise India",
      channelLogoUrl: "https://picsum.photos/seed/moneywise/96/96",
      channelProfileSlug: "moneywise-india",
      budget: "₹3,000–₹4,500 per video",
      workMode: "Monthly · Remote",
      location: "Remote",
      experience: "3–5 years",
      tags: ["Premiere", "Documentary", "B-roll", "Sound design"],
listingStatus: "Open",
      creator: {
        platforms: ["youtube"],
        formats: ["Long-form video"],
        niches: ["Finance", "True Crime"],
        turnaround: { value: 2, unit: "weeks", basis: "final_delivery" },
        compensation: { mode: "unpaid", unit: "unpaid", note: "Portfolio credit and a channel shout-out." },
        channelHandle: "moneywise-india",
        employerKind: "creator",
        subscribers: 54000,
        cadence: "2 videos/month",
      },
    },
    timeline: [
      { id: "t-app-sent-5-applied", label: "Application sent", occurredAt: ago(518400) },
      { id: "t-app-sent-5-viewed", label: "Viewed by Moneywise India", occurredAt: ago(259200) },
      { id: "t-app-sent-5-shortlisted", label: "Shortlisted by Moneywise India", occurredAt: ago(86400) },
    ],
  },

  // ---- Talent mode: hiring requests this user received on their talent listing ----
  {
    id: "t-req-recv-1",
    mode: "talent",
    direction: "received",
    kind: "hiring_request",
    status: "new",
    managerNote: "Daily channel — confirm the Monday handoff works before accepting.",
    title: "Shorts editing package — 15 shorts per month",
    counterpartyName: "Motivation Shorts",
    counterpartyAvatarUrl: "https://picsum.photos/seed/motivation/96/96",
    createdAt: ago(86400),
    updatedAt: ago(86400),
    unread: true,
    message:
      "Hi, I came across your listing and would like to discuss a monthly Shorts package.",
    // Structured answers to the talent's first-message requirements (talent context).
    firstMessageAnswers: {
      project_budget: { amount: "1,400", unit: "per month" },
      project_brief:
        "15 Shorts per month in our house caption style. Scripts and raw clips are ready every Monday; 2 revision rounds per short.",
      turnaround: { value: "2", unit: "days" },
      working_hours: "Weekly delivery",
      channel_or_brand_link: "https://youtube.com/@motivationshorts",
      reference_links: [
        {
          url: "https://www.youtube.com/watch?v=9bZkp7q19f0",
          title: "Fast-paced motivation short",
          note: "Match the pacing, punch-in captions, and quick motivational payoff.",
          timestampNotes: [
            { time: "0:03", seconds: 3, title: "Hook", description: "Opens on the payoff line, not a slow build." },
            { time: "0:18", seconds: 18, title: "Caption density", description: "Two-word punch-in captions synced to the beat." },
          ],
        },
        {
          url: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
          title: "Caption + sound benchmark",
          note: "Use this as the sound-design and music-ducking benchmark.",
          timestampNotes: [
            { time: "0:24", seconds: 24, title: "Music duck", description: "Music dips under the voice line — match this feel." },
          ],
        },
      ],
      start_availability: "Immediately",
      fit_note: "Your retention work fits our daily channel and we already have a steady content pipeline.",
      custom_instruction: {
        prompt: "Share the channel context, one reference to match, and what success would look like in the first month.",
        response:
          "This is for a daily motivation Shorts channel. We want pacing close to the two references and success means 15 on-brand shorts delivered without daily hand-holding.",
        links: ["https://www.youtube.com/watch?v=9bZkp7q19f0"],
      },
    },
    recruiter: {
      profileSlug: "motivation-shorts",
      name: "Motivation Shorts",
      avatarUrl: "https://picsum.photos/seed/motivation/96/96",
      channelName: "Motivation Shorts",
      audienceLabel: "412K subscribers",
      platform: "YouTube",
      hiringFor: "Daily faceless shorts channel",
    },
    sourceListingTitle: "Retention-focused long-form and shorts editing",
    talent: OWN_TALENT_LISTING_SNAPSHOT,
    timeline: [{ id: "t-req-recv-1-sent", label: "Request received", occurredAt: ago(86400) }],
  },
  {
    id: "t-req-recv-2",
    mode: "talent",
    direction: "received",
    kind: "hiring_request",
    status: "accepted",
    title: "Monthly retainer — 4 long-form edits",
    counterpartyName: "Finance Channel",
    counterpartyAvatarUrl: "https://picsum.photos/seed/finance/96/96",
    createdAt: ago(259200),
    updatedAt: ago(172800),
    message:
      "We publish one long-form explainer a week and want a single editor who owns pacing, captions, and sound. Your listing matches the brief — open to a monthly retainer starting next cycle.",
    firstMessageAnswers: {
      project_budget: { amount: "3,200", unit: "per month" },
      project_brief:
        "4 long-form finance explainers per month. Scripts and references are ready before kickoff; you own pacing, captions, and sound cleanup.",
      turnaround: { value: "5", unit: "days" },
      working_hours: "Weekly delivery",
      channel_or_brand_link: "https://youtube.com/@financecreator",
      start_availability: "Within 2 weeks",
    },
    response: {
      from: "Finance Channel",
      body: "Great to have you on board. I'll share the first month's scripts and our brand kit on Monday so you can plan the batch.",
      sentAt: ago(172800),
    },
    recruiter: {
      profileSlug: "finance-creator",
      name: "Finance Channel",
      avatarUrl: "https://picsum.photos/seed/finance/96/96",
      channelName: "Finance Channel",
      audienceLabel: "128K subscribers",
      platform: "YouTube",
      hiringFor: "Weekly finance explainers",
    },
    sourceListingTitle: "Retention-focused long-form and shorts editing",
    talent: OWN_TALENT_LISTING_SNAPSHOT,
    timeline: [
      { id: "t-req-recv-2-sent", label: "Request received", occurredAt: ago(259200) },
      { id: "t-req-recv-2-accepted", label: "Accepted by you", occurredAt: ago(172800) },
    ],
  },
  {
    id: "t-req-recv-3",
    mode: "talent",
    direction: "received",
    kind: "hiring_request",
    status: "declined",
    title: "Documentary research + assembly edit",
    counterpartyName: "History Deep Dives",
    counterpartyAvatarUrl: "https://picsum.photos/seed/history/96/96",
    createdAt: ago(604800),
    updatedAt: ago(518400),
    message:
      "Looking for one person to handle source pulls and a first assembly cut for a 25-minute documentary. Timeline is six weeks with weekly check-ins.",
    firstMessageAnswers: {
      project_budget: { amount: "6,000", unit: "per project" },
      project_brief:
        "Source pulls, research board, and first assembly cut for a 25-minute documentary episode.",
      turnaround: { value: "6", unit: "weeks" },
      reference_links: [
        {
          url: "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
          title: "Archival-heavy documentary",
          note: "Reference for archival overlay density and narration pacing — not the exact visual style.",
          timestampNotes: [
            { time: "1:12", seconds: 72, title: "Archival overlay", description: "Layered stills with subtle motion under the VO." },
            { time: "4:30", seconds: 270, title: "Chapter transition", description: "Clean act break with a title card and music swell." },
          ],
        },
        {
          url: "https://vimeo.com/76979871",
          title: "Assembly pacing reference",
          note: "Use this only for the first-assembly rhythm — how scenes are ordered before polish.",
        },
      ],
      fit_note: "Your long-form structure work looks aligned with documentary research-heavy edits.",
    },
    recruiter: {
      profileSlug: "history-deep-dives",
      name: "History Deep Dives",
      avatarUrl: "https://picsum.photos/seed/history/96/96",
      channelName: "History Deep Dives",
      audienceLabel: "208K subscribers",
      platform: "YouTube",
      hiringFor: "Documentary-style deep dives",
    },
    sourceListingTitle: "Retention-focused long-form and shorts editing",
    talent: OWN_TALENT_LISTING_SNAPSHOT,
    timeline: [
      { id: "t-req-recv-3-sent", label: "Request received", occurredAt: ago(604800) },
      { id: "t-req-recv-3-declined", label: "Declined by you", occurredAt: ago(518400) },
    ],
  },
  {
    id: "t-req-recv-4",
    mode: "talent",
    direction: "received",
    kind: "hiring_request",
    status: "pending",
    title: "Thumbnail + packaging help for gaming channel",
    counterpartyName: "Pixel Rush",
    counterpartyAvatarUrl: "https://picsum.photos/seed/pixelrush/96/96",
    createdAt: ago(36000),
    updatedAt: ago(36000),
    unread: true,
    message: "",
    firstMessageAnswers: {
      project_budget: { amount: "1,000", unit: "per month" },
      project_brief: "10 gaming thumbnails per month with two concept directions for each main upload.",
      turnaround: { value: "2", unit: "days" },
      channel_or_brand_link: "https://youtube.com/@pixelrush",
      fit_note: "Your retention and packaging work seems close to the style we need for our gaming channel.",
    },
    recruiter: {
      profileSlug: "pixel-rush",
      name: "Pixel Rush",
      avatarUrl: "https://picsum.photos/seed/pixelrush/96/96",
      channelName: "Pixel Rush",
      audienceLabel: "76K subscribers",
      platform: "YouTube",
      hiringFor: "Gaming highlights channel",
    },
    sourceListingTitle: "Retention-focused long-form and shorts editing",
    talent: OWN_TALENT_LISTING_SNAPSHOT,
    timeline: [{ id: "t-req-recv-4-sent", label: "Request received", occurredAt: ago(36000) }],
  },

  // ---- Recruiter mode: applications received on this user's job listings ----
  {
    id: "r-app-recv-1",
    mode: "hiring",
    direction: "received",
    kind: "application",
    status: "new",
    title: "Aarav Mehta",
    counterpartyName: "Aarav Mehta",
    createdAt: ago(14400),
    updatedAt: ago(14400),
    unread: true,
    message:
      "Hi, I came across the listing and would love to be considered for the long-form editor role.",
    attachments: [
      { label: "Retention case study", url: "https://portfolio.example.com/aarav/case-study" },
    ],
    // Structured answers to the recruiter's first-message requirements (job context).
    firstMessageAnswers: {
      expected_rate: { amount: "2,500", unit: "per video" },
      relevant_portfolio: [
        {
          id: "demo-portfolio-1",
          title: "Retention rebuild — market explainer",
          url: "https://www.youtube.com/watch?v=9bZkp7q19f0",
          type: "Retention edit",
          platform: "YouTube",
          description:
            "Re-cut of a finance explainer that was losing viewers at the intro — new hook, tighter pacing, on-screen callouts.",
          role: "Edit rebuild, hook rewrite, motion callouts",
          metrics: ["Retention 38% → 54%", "1.2M views"],
          tags: ["Retention", "Finance", "Explainer"],
          tools: ["Premiere Pro", "After Effects"],
          timestampNotes: [
            { time: "0:00", seconds: 0, title: "New hook", description: "Original opened on a logo sting; replaced with a question hook." },
            { time: "2:10", seconds: 130, title: "Tightened setup", description: "Removed ~40s of repetition before the first payoff." },
            { time: "5:48", seconds: 348, title: "Motion callouts", description: "On-screen numbers to hold attention through the data." },
          ],
        },
        {
          id: "demo-portfolio-2",
          title: "Series packaging — education channel",
          url: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
          type: "Channel package",
          platform: "YouTube",
          description: "Built a reusable intro, lower-thirds, and end-screen system for a 12-video education series.",
          role: "Motion graphics, template system",
          metrics: ["12-video series", "Motion graphics"],
          tags: ["Motion graphics", "Education"],
          tools: ["After Effects", "Illustrator"],
          timestampNotes: [
            { time: "0:03", seconds: 3, title: "Animated intro", description: "Template intro that re-times to each episode's title." },
            { time: "8:20", seconds: 500, title: "End-screen system", description: "Consistent end-screen with next-video + subscribe." },
          ],
        },
      ],
      turnaround: { value: "4", unit: "days" },
      working_hours: "Evenings IST",
      relevant_experience: "3 years editing weekly finance explainers for two creator-led channels.",
      tools_workflow: ["Premiere Pro", "After Effects", "Audition"],
      start_availability: "Within 1 week",
      fit_note: "I already edit in your niche, so I can match the channel’s pacing from day one.",
    },
    job: {
      jobId: null,
      title: "Long-form editor for weekly finance explainers",
      budget: "₹2,000–₹3,500 per video",
      workMode: "Monthly · Remote",
      location: "Remote",
      experience: "2–4 years",
      tags: ["Long-form", "Retention", "Captions"],
listingStatus: "Open",
      creator: {
        platforms: ["youtube"],
        formats: ["Long-form video"],
        niches: ["Finance", "Education"],
        turnaround: { value: 3, unit: "calendar_days", basis: "first_draft" },
        compensation: { mode: "range", minimum: 2000, maximum: 3500, currency: "INR", unit: "per video" },
        channelHandle: "finance-simplified",
        employerKind: "creator",
        subscribers: 412000,
        cadence: "2 videos/week",
      },
    },
    talent: {
      profileSlug: "aarav-mehta",
      name: "Aarav Mehta",
      headline: "Retention editor for creator-led YouTube channels",
      location: "Mumbai, India",
      availability: "Available · 2 slots this month",
      bio: "I edit long-form videos for finance and education creators, with retention-first structure, tight pacing, and clean caption systems.",
      tools: ["Premiere Pro", "After Effects", "Audition"],
      niches: ["Finance", "Education", "Explainers"],
      experienceNote: "3 yrs editing for creator teams · most recently a weekly finance explainer channel",
      portfolioHighlights: [
        { title: "Retention rebuild — market explainer", detail: "Long-form edit · pacing + caption system" },
        { title: "Series packaging — education channel", detail: "4-video series · structure + sound design" },
      ],
    },
    privateNotes: [
      {
        id: "r-app-recv-1-note-3",
        body: "Portfolio retention numbers check out. Shortlist for a paid test edit on last week's upload.",
        createdAt: "Today, 9:12 AM",
      },
      {
        id: "r-app-recv-1-note-2",
        body: "Asked for the finance A/B board — waiting to see CTR variations before an interview.",
        createdAt: "Yesterday, 6:40 PM",
      },
      {
        id: "r-app-recv-1-note-1",
        body: "Rate is ₹2,500/video, a bit above budget. Worth it if the retention rebuild is real.",
        createdAt: "2 days ago",
      },
    ],
    timeline: [{ id: "r-app-recv-1-applied", label: "Application received", occurredAt: ago(14400) }],
  },
  {
    id: "r-app-recv-2",
    mode: "hiring",
    direction: "received",
    kind: "application",
    status: "viewed",
    managerNote: "Strong packaging systems — ask for the finance A/B board before an interview.",
    title: "Mira Shah",
    counterpartyName: "Mira Shah",
    createdAt: ago(86400),
    updatedAt: ago(28800),
    message:
      "I design CTR-focused thumbnails for tech and finance channels — 3 concepts per video with mobile-size legibility checks. I can slot into your weekly publish schedule and keep a shared concept board for fast approvals.",
    firstMessageAnswers: {
      expected_rate: { amount: "1,000", unit: "per month" },
      relevant_portfolio: [
        {
          id: "mira-packaging-board",
          title: "Finance thumbnail A/B set",
          url: "https://portfolio.example.com/thumbnails/finance-ab-test",
          type: "Thumbnail set",
          platform: "YouTube",
          description: "12 thumbnail concepts for a finance channel with CTR-oriented layout variations tested over 4 weeks.",
          role: "Concepting, design, A/B testing",
          metrics: ["12 thumbnails tested", "CTR 4.1% → 6.8%"],
          tags: ["CTR", "Finance", "YouTube"],
          tools: ["Photoshop", "Figma", "Midjourney"],
        },
        {
          id: "mira-tech-packaging",
          title: "Packaging refresh — tech reviews",
          url: "https://portfolio.example.com/thumbnails/tech-packaging",
          type: "Thumbnail set",
          platform: "YouTube",
          description: "Rebuilt title + thumbnail system for a tech-review channel to improve mobile legibility.",
          role: "Design system, mobile legibility pass",
          tags: ["CTR", "Tech"],
          tools: ["Photoshop", "Illustrator"],
        },
      ],
      relevant_experience: "Packaging systems for 6 channels, usually 3 concepts per video within 24 hours.",
      tools_workflow: ["Photoshop", "Figma", "Illustrator"],
      fit_note: "Your weekly explainer cadence matches how I run thumbnail boards for retainers.",
    },
    job: {
      jobId: null,
      title: "Thumbnail designer for weekly explainers",
      budget: "₹800–₹1,400 per month",
      workMode: "Monthly · Remote",
      location: "Remote",
      experience: "1–3 years",
      tags: ["Thumbnails", "CTR", "Packaging"],
listingStatus: "Open",
      creator: {
        platforms: ["youtube"],
        formats: ["Thumbnails"],
        niches: ["Finance"],
        turnaround: { value: 2, unit: "business_days", basis: "per_deliverable" },
        compensation: { mode: "fixed", minimum: 1200, currency: "INR", unit: "per thumbnail" },
        channelHandle: "finance-simplified",
        employerKind: "creator",
        subscribers: 412000,
        cadence: "2 videos/week",
      },
    },
    talent: {
      profileSlug: "mira-shah",
      name: "Mira Shah",
      headline: "CTR-focused thumbnail designer for tech and finance",
      location: "Pune, India",
      availability: "Selective · taking 1 retainer",
      bio: "Thumbnail systems with strong visual hierarchy, fast concept iteration, and consistent packaging across a channel.",
      tools: ["Photoshop", "Figma", "Illustrator"],
      niches: ["Tech", "Finance", "Productivity"],
      experienceNote: "Packaging for 6 channels · concept-to-approval in 24h",
      portfolioHighlights: [
        { title: "Packaging refresh — tech reviews", detail: "Channel-wide thumbnail system" },
        { title: "A/B concept board — finance series", detail: "3 concepts per video · weekly cadence" },
      ],
    },
    timeline: [
      { id: "r-app-recv-2-applied", label: "Application received", occurredAt: ago(86400) },
      { id: "r-app-recv-2-viewed", label: "Viewed by you", occurredAt: ago(86400) },
      { id: "r-app-recv-2-shortlisted", label: "Shortlisted by you", occurredAt: ago(28800) },
    ],
  },
  {
    id: "r-app-recv-3",
    mode: "hiring",
    direction: "received",
    kind: "application",
    status: "declined",
    title: "Dev Patel",
    counterpartyName: "Dev Patel",
    createdAt: ago(432000),
    updatedAt: ago(259200),
    message:
      "I manage uploads, analytics reviews, and a content calendar for two channels. I can take over your publishing ops end to end, including QA before every upload and a weekly metrics summary.",
    proposedTerms: "₹2,400 per month · part-time",
    job: {
      jobId: null,
      title: "Channel ops manager (part-time)",
      budget: "₹2,000–₹3,000 per month",
      workMode: "Part-time · Remote",
      location: "Remote",
      experience: "2–4 years",
      tags: ["Channel ops", "Analytics", "Calendar"],
listingStatus: "Closed",
      creator: {
        platforms: ["youtube", "instagram"],
        formats: ["Content strategy"],
        niches: ["Technology"],
        turnaround: { value: 1, unit: "weeks", basis: "final_delivery" },
        compensation: { mode: "fixed", minimum: 45000, currency: "INR", unit: "per month" },
        channelHandle: "tech-unpacked",
        employerKind: "agency",
        subscribers: 1300000,
        cadence: "3 videos/week",
      },
    },
    talent: {
      profileSlug: "dev-patel",
      name: "Dev Patel",
      headline: "Channel manager for uploads, analytics, and content calendar",
      location: "Ahmedabad, India",
      availability: "Available",
      bio: "I keep publishing pipelines on schedule — upload QA, metadata, analytics reviews, and team coordination.",
      tools: ["YouTube Studio", "Notion", "Sheets"],
      niches: ["Education", "Business"],
      experienceNote: "2 yrs running ops for multi-editor channels",
      portfolioHighlights: [
        { title: "Publishing pipeline — weekly channel", detail: "Upload QA + metadata system" },
      ],
    },
    timeline: [
      { id: "r-app-recv-3-applied", label: "Application received", occurredAt: ago(432000) },
      { id: "r-app-recv-3-viewed", label: "Viewed by you", occurredAt: ago(345600) },
      { id: "r-app-recv-3-declined", label: "Declined by you", occurredAt: ago(259200) },
    ],
  },
  {
    id: "r-app-recv-4",
    mode: "hiring",
    direction: "received",
    kind: "application",
    status: "responded",
    title: "Rhea Kapoor",
    counterpartyName: "Rhea Kapoor",
    createdAt: ago(172800),
    updatedAt: ago(21600),
    unread: true,
    message:
      "I edit shorts and long-form for education channels and can own your weekly batch. I've attached a before/after where I lifted average view duration by reworking the first 30 seconds.",
    firstMessageAnswers: {
      expected_rate: { amount: "2,200", unit: "per video" },
      relevant_portfolio: [
        {
          id: "rhea-before-after",
          title: "Retention rework — first 30 seconds",
          url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          type: "Retention edit",
          platform: "YouTube",
          description:
            "Before/after of an education video's opening: rewrote the hook, cut dead air, and added a cold-open payoff.",
          role: "Re-edit, hook rewrite",
          metrics: ["Avg view duration +34%", "Before/after included"],
          tags: ["Retention", "Education", "Hook"],
          tools: ["Final Cut Pro", "Motion"],
          timestampNotes: [
            { time: "0:00", seconds: 0, title: "Before", description: "Original opening — slow logo intro and a soft question." },
            { time: "0:32", seconds: 32, title: "After", description: "Reworked cold open with a payoff promise in the first line." },
          ],
        },
      ],
      turnaround: { value: "4", unit: "days" },
      working_hours: "Flexible hours",
      start_availability: "Next Monday",
    },
    job: {
      jobId: null,
      title: "Long-form editor for weekly finance explainers",
      budget: "₹2,000–₹3,500 per video",
      workMode: "Monthly · Remote",
      location: "Remote",
      experience: "2–4 years",
      tags: ["Long-form", "Retention", "Captions"],
listingStatus: "Open",
      creator: {
        platforms: ["youtube"],
        formats: ["Long-form video"],
        niches: ["Finance", "Education"],
        turnaround: { value: 3, unit: "calendar_days", basis: "first_draft" },
        compensation: { mode: "range", minimum: 2000, maximum: 3500, currency: "INR", unit: "per video" },
        channelHandle: "finance-simplified",
        employerKind: "creator",
        subscribers: 412000,
        cadence: "2 videos/week",
      },
    },
    response: {
      from: "You",
      body: "Thanks Rhea — the before/after is strong. Can you share two shorts examples with the before/after edits?",
      sentAt: ago(86400),
    },
    replies: [
      {
        from: "Rhea Kapoor",
        body: "Sent — here are two shorts with the raw and final side by side. I'm available from next Monday and can take 3 videos per week.",
        sentAt: ago(21600),
      },
    ],
    talent: {
      profileSlug: "rhea-kapoor",
      name: "Rhea Kapoor",
      headline: "Retention editor for education and finance channels",
      location: "Delhi, India",
      availability: "Available from next Monday",
      bio: "I focus on the first 30 seconds and pacing structure to lift average view duration, with clean captions and mixed audio.",
      tools: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
      niches: ["Education", "Finance"],
      experienceNote: "3 yrs editing weekly batches for creator channels",
      portfolioHighlights: [
        { title: "Retention rework — intro 30s", detail: "Before/after · +18% AVD" },
      ],
    },
    timeline: [
      { id: "r-app-recv-4-applied", label: "Application received", occurredAt: ago(172800) },
      { id: "r-app-recv-4-viewed", label: "Viewed by you", occurredAt: ago(172800) },
      { id: "r-app-recv-4-responded", label: "Reply sent", occurredAt: ago(86400) },
      { id: "r-app-recv-4-candidate", label: "Candidate responded", occurredAt: ago(21600) },
    ],
  },
  {
    id: "r-app-recv-5",
    mode: "hiring",
    direction: "received",
    kind: "application",
    status: "new",
    title: "Ishaan Verma",
    counterpartyName: "Ishaan Verma",
    createdAt: ago(28800),
    updatedAt: ago(28800),
    unread: true,
    message:
      "I've spent three years on creator-led finance and tech channels doing long-form edits, motion callouts, and thumbnail packaging. I work hook-first, keep a shared review board, and can deliver a paid test edit on a recent upload before you commit to anything.",
    firstMessageAnswers: {
      expected_rate: { amount: "3,000", unit: "per video" },
      relevant_portfolio: [
        {
          id: "ishaan-showreel",
          title: "Showreel — finance long-form",
          url: "https://portfolio.example.com/ishaan/showreel",
        },
        {
          id: "ishaan-thumbnails",
          title: "Thumbnail packaging set",
          url: "https://portfolio.example.com/ishaan/thumbnails",
        },
      ],
      turnaround: { value: "3", unit: "days" },
      relevant_experience: "3 years on creator-led finance and tech channels from 80K to 1.2M subscribers.",
      tools_workflow: ["Premiere Pro", "After Effects", "Photoshop", "Figma"],
      custom_instruction: {
        prompt: "Share how you would improve the first 30 seconds of a finance explainer.",
        response:
          "I would isolate the core viewer question, open on the consequence, then use a fast proof clip before the first chart so the video earns the analytical section.",
        links: ["https://portfolio.example.com/ishaan/showreel"],
      },
    },
    attachments: [
      { label: "Showreel — finance long-form", url: "https://portfolio.example.com/ishaan/showreel" },
      { label: "Thumbnail packaging set", url: "https://portfolio.example.com/ishaan/thumbnails" },
    ],
    job: {
      jobId: null,
      title: "Long-form editor for weekly finance explainers",
      budget: "₹2,000–₹3,500 per video",
      workMode: "Monthly · Remote",
      location: "Remote",
      experience: "2–4 years",
      tags: ["Long-form", "Retention", "Captions"],
listingStatus: "Open",
      creator: {
        platforms: ["youtube"],
        formats: ["Long-form video"],
        niches: ["Finance", "Education"],
        turnaround: { value: 3, unit: "calendar_days", basis: "first_draft" },
        compensation: { mode: "range", minimum: 2000, maximum: 3500, currency: "INR", unit: "per video" },
        channelHandle: "finance-simplified",
        employerKind: "creator",
        subscribers: 412000,
        cadence: "2 videos/week",
      },
    },
    talent: {
      profileSlug: "ishaan-verma",
      name: "Ishaan Verma",
      headline: "Senior editor + packaging for finance and tech creators",
      location: "Bengaluru, India · IST",
      availability: "Available · 2 slots this month",
      bio: "Long-form editing with retention-first structure, motion callouts, and CTR-focused thumbnail packaging. I run a shared review board so approvals stay fast across a channel team.",
      tools: ["Premiere Pro", "After Effects", "Photoshop", "Figma"],
      niches: ["Finance", "Tech", "Explainers"],
      experienceNote: "3 yrs · creator-led channels from 80K to 1.2M subs",
      portfolioHighlights: [
        { title: "Retention rebuild — market explainer", detail: "Long-form edit · pacing + caption system" },
        { title: "Motion callout system — tech reviews", detail: "Reusable AE templates" },
        { title: "Packaging refresh — finance series", detail: "Channel-wide thumbnail system" },
      ],
    },
    timeline: [{ id: "r-app-recv-5-applied", label: "Application received", occurredAt: ago(28800) }],
  },
  {
    id: "r-app-recv-6",
    mode: "hiring",
    direction: "received",
    kind: "application",
    status: "closed",
    archivedAt: "2026-05-22T09:00:00.000Z",
    title: "Sana Khan",
    counterpartyName: "Sana Khan",
    createdAt: ago(2592000),
    updatedAt: ago(1814400),
    message: "",
    job: {
      jobId: null,
      title: "Channel ops manager (part-time)",
      budget: "₹2,000–₹3,000 per month",
      workMode: "Part-time · Remote",
      location: "Remote",
      experience: "1–2 years",
      tags: ["Channel ops", "Scheduling"],
listingStatus: "Closed",
      creator: {
        platforms: ["youtube", "instagram"],
        formats: ["Content strategy"],
        niches: ["Technology"],
        turnaround: { value: 1, unit: "weeks", basis: "final_delivery" },
        compensation: { mode: "fixed", minimum: 45000, currency: "INR", unit: "per month" },
        channelHandle: "tech-unpacked",
        employerKind: "agency",
        subscribers: 1300000,
        cadence: "3 videos/week",
      },
    },
    talent: {
      profileSlug: "sana-khan",
      name: "Sana Khan",
      headline: "Channel coordinator — scheduling and uploads",
      location: "Hyderabad, India",
      availability: null,
      bio: null,
      tools: ["YouTube Studio", "Notion"],
      niches: ["Education"],
      experienceNote: null,
      portfolioHighlights: [],
    },
    timeline: [
      { id: "r-app-recv-6-applied", label: "Application received", occurredAt: ago(2592000) },
      { id: "r-app-recv-6-archived", label: "Archived", occurredAt: ago(1814400) },
    ],
  },

  // ---- Recruiter mode: hiring requests this user sent to talent ----
  {
    id: "r-req-sent-1",
    mode: "hiring",
    direction: "sent",
    kind: "hiring_request",
    status: "pending",
    title: "Anika Rao",
    contextLabel: "Shorts editing package — 15 shorts per month",
    counterpartyName: "Anika Rao",
    createdAt: ago(86400),
    updatedAt: ago(86400),
    message:
      "Your shorts work fits our daily channel. We need 15 shorts a month in a consistent caption style — raw clips and scripts arrive every Monday. Are you open to a trial month?",
    firstMessageAnswers: {
      project_budget: { amount: "1,400", unit: "per month" },
      project_brief:
        "15 Shorts per month in a consistent caption style. Raw clips and scripts arrive every Monday.",
      turnaround: { value: "2", unit: "days" },
      working_hours: "Weekly delivery",
      channel_or_brand_link: "https://youtube.com/@motivationshorts",
      reference_links: [
        {
          url: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
          title: "Caption style to match",
          note: "Match this caption density and the punch-in timing on the beat.",
          timestampNotes: [
            { time: "0:06", seconds: 6, title: "Caption rhythm", description: "Captions land on stressed words, not every word." },
          ],
        },
      ],
      start_availability: "Immediately",
      fit_note: "Your daily shorts systems are close to the workflow we need.",
      custom_instruction: {
        prompt: "Share the channel context, one reference to match, and what success would look like in the first month.",
        response:
          "This is a daily faceless motivation channel. We want the captions and pacing matched to the reference, with the first month measured by consistent delivery and stable retention.",
        links: ["https://www.youtube.com/watch?v=jNQXAC9IVRw"],
      },
    },
    talent: {
      profileSlug: "anika-rao",
      name: "Anika Rao",
      headline: "Shorts editor for daily faceless channels",
      rate: "₹15,000 per month",
      experience: "3 years",
      location: "Bengaluru, India",
      availability: "Available · evenings IST",
      tools: ["CapCut", "Premiere Pro"],
      niches: ["Fitness", "Motivation", "Shorts"],
      experienceNote: "Daily shorts pipelines for 3 faceless channels",
      portfolioHighlights: [
        { title: "Daily shorts system — fitness channel", detail: "Hook-first cuts · caption templates" },
      ],
    },
    timeline: [{ id: "r-req-sent-1-sent", label: "Request sent", occurredAt: ago(86400) }],
  },
  {
    id: "r-req-sent-2",
    mode: "hiring",
    direction: "sent",
    kind: "hiring_request",
    status: "responded",
    title: "Kabir Sen",
    contextLabel: "Scriptwriting — 6-part explainer series",
    counterpartyName: "Kabir Sen",
    createdAt: ago(172800),
    updatedAt: ago(32400),
    unread: true,
    message:
      "We're planning a 6-part explainer series and need outlines plus full scripts with sourced claims. Two scripts a month, research notes included. Would this fit your current load?",
    firstMessageAnswers: {
      project_budget: { amount: "1,800", unit: "per video" },
      project_brief:
        "A 6-part explainer series: outlines, full scripts, sourced claims, and research notes for two scripts per month.",
      turnaround: { value: "2", unit: "weeks" },
      working_hours: "Flexible hours",
      channel_or_brand_link: "https://youtube.com/@contentbusiness",
      reference_links: [
        {
          url: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
          title: "Explainer intro structure",
          note: "Use the intro structure only — question, stakes, then roadmap.",
          timestampNotes: [
            { time: "0:00", seconds: 0, title: "Question first", description: "States the viewer question before any branding." },
            { time: "0:40", seconds: 40, title: "Roadmap", description: "Previews the three sections to set expectations." },
          ],
        },
        {
          url: "https://drive.google.com/file/d/1mock-broll-density/view",
          title: "B-roll density doc",
          note: "Our target B-roll density per minute — reference only, not pacing.",
        },
      ],
      start_availability: "Within 1 week",
    },
    response: {
      from: "Kabir Sen",
      body: "This fits my schedule from next month. I can send a sample outline for your first topic this week so you can check structure and sourcing style.",
      sentAt: ago(32400),
    },
    replies: [
      {
        from: "You",
        body: "That works. Let's start with the AI-regulation explainer — I'll drop the brief and reference links in a shared doc today.",
        sentAt: ago(25200),
      },
      {
        from: "Kabir Sen",
        body: "Got the brief, thanks. I'll have the outline and sourced notes back to you within two days.",
        sentAt: ago(18000),
      },
    ],
    talent: {
      profileSlug: "kabir-sen",
      name: "Kabir Sen",
      headline: "Scriptwriter for explainers, documentary hooks, and outlines",
      rate: "₹8,000 per script",
      experience: "4 years",
      location: "Kolkata, India",
      availability: "Selective · 2 scripts per month",
      tools: ["Notion", "Google Docs"],
      niches: ["Documentary", "Explainers", "History"],
      experienceNote: "Scripts and outlines for deep-dive channels with sourced research",
      portfolioHighlights: [
        { title: "6-part series outline — history channel", detail: "Structure + sourced research notes" },
      ],
    },
    timeline: [
      { id: "r-req-sent-2-sent", label: "Request sent", occurredAt: ago(172800) },
      { id: "r-req-sent-2-viewed", label: "Viewed by Kabir Sen", occurredAt: ago(86400) },
      { id: "r-req-sent-2-responded", label: "Response received", occurredAt: ago(32400) },
    ],
  },
  {
    id: "r-req-sent-3",
    mode: "hiring",
    direction: "sent",
    kind: "hiring_request",
    status: "declined",
    title: "Nora Chen",
    contextLabel: "Motion graphics — callouts + kinetic text",
    counterpartyName: "Nora Chen",
    createdAt: ago(604800),
    updatedAt: ago(432000),
    message:
      "We want animated callouts and kinetic text for two videos a month — your lower-thirds style matches our brand. Open to a per-video arrangement?",
    firstMessageAnswers: {
      project_budget: { amount: "900", unit: "per video" },
      project_brief: "Animated callouts and kinetic text for two explainers per month.",
      reference_links: [
        {
          url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          title: "Lower-thirds + kinetic text",
          note: "Reference for lower-thirds motion and kinetic-text timing.",
          timestampNotes: [
            { time: "0:14", seconds: 14, title: "Lower-third in", description: "Ease-in with a subtle blur — match this weight." },
            { time: "1:02", seconds: 62, title: "Kinetic emphasis", description: "Key words scale up on beat without feeling busy." },
          ],
        },
      ],
      fit_note: "Your lower-thirds style matches the visual language we want.",
    },
    response: {
      from: "Nora Chen",
      body: "Thanks for thinking of me — your channel looks great. I'm fully booked through next quarter, but I'd be glad to revisit after that.",
      sentAt: ago(432000),
    },
    talent: {
      profileSlug: "nora-chen",
      name: "Nora Chen",
      headline: "Motion designer for callouts, lower thirds, and kinetic text",
      rate: "₹12,000 per project",
      experience: "5 years",
      location: "Singapore",
      availability: "Unavailable until next quarter",
      tools: ["After Effects", "Illustrator"],
      niches: ["Science", "Education"],
      experienceNote: "Motion systems for explainer channels",
      portfolioHighlights: [
        { title: "Callout system — science channel", detail: "Reusable AE templates" },
      ],
    },
    timeline: [
      { id: "r-req-sent-3-sent", label: "Request sent", occurredAt: ago(604800) },
      { id: "r-req-sent-3-viewed", label: "Viewed by Nora Chen", occurredAt: ago(518400) },
      { id: "r-req-sent-3-declined", label: "Declined by Nora Chen", occurredAt: ago(432000) },
    ],
  },
  {
    id: "r-req-sent-4",
    mode: "hiring",
    direction: "sent",
    kind: "hiring_request",
    status: "accepted",
    title: "Tara Iyer",
    contextLabel: "Thumbnail packaging — weekly retainer",
    counterpartyName: "Tara Iyer",
    createdAt: ago(345600),
    updatedAt: ago(172800),
    message:
      "Your packaging board for tech channels is exactly our style. We publish twice a week and want 8 thumbnails a month with a shared concept board for fast approvals. Open to a retainer?",
    firstMessageAnswers: {
      project_budget: { amount: "1,200", unit: "per month" },
      project_brief:
        "8 thumbnails per month with a shared concept board and fast approvals for two uploads per week.",
      working_hours: "Mornings IST",
      channel_or_brand_link: "https://youtube.com/@techchannel",
      start_availability: "Within 1 week",
      fit_note: "Your packaging board for tech channels is exactly our style.",
    },
    response: {
      from: "Tara Iyer",
      body: "Yes, I'd love to. I can start this week — I'll set up a shared board and send the first two concepts for your next upload.",
      sentAt: ago(172800),
    },
    talent: {
      profileSlug: "tara-iyer",
      name: "Tara Iyer",
      headline: "Thumbnail designer + packaging for tech and finance channels",
      rate: "₹1,500 per thumbnail",
      experience: "4 years",
      location: "Chennai, India",
      availability: "Available · 1 retainer slot",
      tools: ["Photoshop", "Figma"],
      niches: ["Tech", "Finance", "Productivity"],
      experienceNote: "Packaging systems with A/B concept boards",
      portfolioHighlights: [
        { title: "Concept board — tech reviews", detail: "3 concepts per video · weekly cadence" },
      ],
    },
    timeline: [
      { id: "r-req-sent-4-sent", label: "Request sent", occurredAt: ago(345600) },
      { id: "r-req-sent-4-viewed", label: "Viewed by Tara Iyer", occurredAt: ago(259200) },
      { id: "r-req-sent-4-accepted", label: "Accepted by Tara Iyer", occurredAt: ago(172800) },
    ],
  },
  {
    id: "r-req-sent-5",
    mode: "hiring",
    direction: "sent",
    kind: "hiring_request",
    status: "withdrawn",
    title: "Arjun Nair",
    contextLabel: "Voice over — horror stories narration",
    counterpartyName: "Arjun Nair",
    createdAt: ago(1814400),
    updatedAt: ago(1209600),
    message:
      "We're starting a horror-stories channel and need a deep, measured narration voice for weekly 10-minute episodes. Your demo fits the mood — would you be open to a per-episode rate?",
    firstMessageAnswers: {
      project_budget: { amount: "1,500", unit: "per video" },
      project_brief: "Weekly 10-minute horror story narration with a deep, measured tone.",
      turnaround: { value: "3", unit: "days" },
      channel_or_brand_link: "https://youtube.com/@nightstories",
    },
    talent: {
      profileSlug: "arjun-nair",
      name: "Arjun Nair",
      headline: "Voice over artist — narration for horror and documentary",
      rate: "₹2,500 per episode",
      experience: "5 years",
      location: "Kochi, India",
      availability: "Selective",
      tools: ["Audition", "Home studio"],
      niches: ["Horror", "Documentary", "Narration"],
      experienceNote: "Narration for story-driven channels",
      portfolioHighlights: [],
    },
    timeline: [
      { id: "r-req-sent-5-sent", label: "Request sent", occurredAt: ago(1814400) },
      { id: "r-req-sent-5-withdrawn", label: "Request withdrawn by you", occurredAt: ago(1209600) },
    ],
  },
];
