"""Facts a page prints under a label, when its markup is silent or wrong.

Structured markup is normally the best evidence a page offers, and the import
pipeline treats it that way. But markup is generated by whoever syndicated the
listing, while the labelled copy is written by the employer — and when those two
disagree, the employer is describing their own job.

One live page made the cost concrete. Its JSON-LD carried no compensation at all
and declared ``employmentType: INTERN``. Its visible copy said:

    Compensation   ₹5,000 / mo
    Type           Part-time / Freelance

CreatorJobs read the markup faithfully and produced a draft with no pay — so it
asked the recruiter how pay was measured, about a page that had answered exactly
that — and an engagement of "internship" for a paid freelance brief.

So a small set of labels is read from the visible text: the ones where a page
states a fact plainly, in a form there is no reasonable second reading of. This
is not a second extractor. It answers "did the employer print this under a
label?", and nothing else.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Final

#: Label rows a job page prints, and the field each one settles.
#:
#: Deliberately short. Every entry here has to be a label whose meaning is the
#: same on any site — "Compensation", "Type", "Location". Anything needing
#: interpretation belongs to the model, not to this.
_LABELS: Final[tuple[tuple[str, str], ...]] = (
    ("compensation", r"(?:compensation|salary|pay|stipend|budget)"),
    ("engagement", r"(?:job\s+type|employment\s+type|type|engagement)"),
)

#: "Compensation ₹5,000 / mo" — label, then value, on one line or the next.
def _label_pattern(label: str) -> re.Pattern[str]:
    return re.compile(
        rf"^[ \t]*{label}[ \t]*[:\-–]?[ \t]*\n?[ \t]*(?P<value>[^\n]{{1,120}})$",
        re.IGNORECASE | re.MULTILINE,
    )


#: Wording that names a supported engagement. Ordered so the more specific
#: reading wins: "part-time / freelance" is freelance work at part-time volume,
#: and the freelance half is what decides how the offer is structured.
_ENGAGEMENT_WORDS: Final[tuple[tuple[str, str], ...]] = (
    ("internship", "internship"),
    ("intern", "internship"),
    ("freelance", "ongoing_freelance"),
    ("contract", "fixed_term"),
    ("part-time", "part_time"),
    ("part time", "part_time"),
    ("full-time", "full_time"),
    ("full time", "full_time"),
    ("retainer", "retainer"),
    ("permanent", "full_time"),
)

#: "₹5,000 / mo", "$30 per hour", "INR 40000 monthly", "Rs. 5,000 per month".
#:
#: Three families of miss were found by generating every currency × period ×
#: amount × spacing rendering rather than listing strings, and all three cost a
#: stated rate entirely — which then produced a question about pay the employer
#: had already printed:
#:
#: * ``Rs`` and ``Rs.`` were not currencies at all, though on Indian job boards
#:   they are at least as common as ``₹``. Eighty currency/period pairs.
#: * ``an`` is the article in "$40 an hour" and was not a separator, so the
#:   period never matched.
#: * ``annual`` without its ``-ly`` was not a period.
#:
#: The ``a``/``an`` separators need their word boundary. Without it ``a`` ate the
#: first letter of the period itself: "₹500000 annually" left "nnually".
_AMOUNT = re.compile(
    r"(?P<symbol>[₹$€£])?\s*(?P<currency>INR|USD|EUR|GBP|AED|SGD|Rs\.?)?\s*"
    r"(?P<amount>\d[\d,\.]*)\s*"
    r"(?:(?P<sep>/|per|an\b|a\b)\s*)?"
    r"(?P<unit>mo|month|monthly|hr|hour|hourly|yr|year|yearly|annually|annual|"
    r"annum|week|weekly|day|daily|project|video|piece|post|episode)?",
    re.IGNORECASE,
)

_SYMBOL_CURRENCY: Final[dict[str, str]] = {"₹": "INR", "$": "USD", "€": "EUR", "£": "GBP"}

#: Currency words that are not already the code the product stores.
_CURRENCY_WORDS: Final[dict[str, str]] = {"rs": "INR", "rs.": "INR"}

#: How a stated period maps onto the product's own units.
_UNITS: Final[dict[str, str]] = {
    "mo": "per month", "month": "per month", "monthly": "per month",
    "hr": "per hour", "hour": "per hour", "hourly": "per hour",
    "yr": "per year", "year": "per year", "yearly": "per year",
    "annual": "per year", "annually": "per year", "annum": "per year",
    "week": "per week", "weekly": "per week",
    "day": "per day", "daily": "per day",
    "project": "per project", "video": "per video", "piece": "per deliverable",
    "post": "per post", "episode": "per episode",
}


@dataclass(frozen=True)
class LabelledFacts:
    """What the page printed under a label, in the product's own vocabulary."""

    engagement_type: str | None = None
    budget_amount: int | None = None
    budget_currency: str | None = None
    budget_unit: str | None = None
    compensation_mode: str | None = None
    #: The exact line each value came from, for evidence.
    evidence: dict[str, str] | None = None


def _read_engagement(value: str) -> str | None:
    lowered = value.casefold()
    # "Part-time / Freelance" names two. Freelance decides how the engagement is
    # structured; part-time only describes its volume, which weekly hours carry.
    if "freelance" in lowered:
        return "ongoing_freelance"
    for word, engagement in _ENGAGEMENT_WORDS:
        if word in lowered:
            return engagement
    return None


def _read_compensation(value: str) -> tuple[int, str, str] | None:
    """A single stated figure with its currency and period, or nothing."""

    match = _AMOUNT.search(value)
    if not match:
        return None
    raw = match.group("amount").replace(",", "").rstrip(".")
    if not raw.isdigit():
        return None
    amount = int(raw)
    currency = match.group("currency")
    if currency:
        # "Rs" is how a page writes rupees; "INR" is how the product stores them.
        currency = _CURRENCY_WORDS.get(currency.casefold(), currency.upper())
    else:
        symbol = match.group("symbol")
        currency = _SYMBOL_CURRENCY.get(symbol or "")
    unit = _UNITS.get((match.group("unit") or "").casefold())
    if not (currency and unit):
        # A bare number is not a rate. Guessing its period is exactly the kind
        # of invention the rest of the pipeline refuses to make.
        return None
    return amount, currency, unit


def labelled_facts(normalized_text: str | None) -> LabelledFacts:
    """Read the handful of facts a page states plainly under a label."""

    text = normalized_text or ""
    if not text.strip():
        return LabelledFacts()

    found: dict[str, object] = {}
    evidence: dict[str, str] = {}

    for name, label in _LABELS:
        match = _label_pattern(label).search(text)
        if not match:
            continue
        value = match.group("value").strip()
        if not value:
            continue

        if name == "engagement":
            engagement = _read_engagement(value)
            if engagement:
                found["engagement_type"] = engagement
                evidence["engagement_type"] = value
        elif name == "compensation":
            money = _read_compensation(value)
            if money:
                amount, currency, unit = money
                found["budget_amount"] = amount
                found["budget_currency"] = currency
                found["budget_unit"] = unit
                # One figure is a fixed rate, not a range. Inventing a second
                # bound would advertise a spread the employer never offered.
                found["compensation_mode"] = "fixed"
                evidence["compensation"] = value

    return LabelledFacts(
        engagement_type=found.get("engagement_type"),  # type: ignore[arg-type]
        budget_amount=found.get("budget_amount"),  # type: ignore[arg-type]
        budget_currency=found.get("budget_currency"),  # type: ignore[arg-type]
        budget_unit=found.get("budget_unit"),  # type: ignore[arg-type]
        compensation_mode=found.get("compensation_mode"),  # type: ignore[arg-type]
        evidence=evidence or None,
    )
