"""Facts a page prints under a label, when its markup is silent or wrong.

Structured markup is normally the best evidence a page offers, and the import
pipeline treats it that way. But markup is generated by whoever syndicated the
listing, while the labelled copy is written by the employer — and when those two
disagree, the employer is describing their own job.

One live page made the cost concrete. Its JSON-LD carried no compensation at all
and declared ``employmentType: INTERN``. Its visible copy said:

    Compensation   ₹5,000 / mo
    Type           Part-time / Freelance

CreatorJobs read the markup faithfully and produced a draft with no pay — so it
asked the recruiter how pay was measured, about a page that had answered exactly
that — and an engagement of "internship" for a paid freelance brief.

So a small set of labels is read from the visible text: the ones where a page
states a fact plainly, in a form there is no reasonable second reading of. This
is not a second extractor. It answers "did the employer print this under a
label?", and nothing else.

Pay is the one exception, and it was earned. A listing headed ``Up to ₹20,000 a
month`` arrived with no pay and a question about pay, because that figure is not
under a label — it is a bare line, which is how most boards render it. So
compensation is also read from the job's own text when no label carries it,
using the grammar in :mod:`app.core.job_import_compensation`. The search stays
inside :func:`primary_job_text`, so a neighbouring listing's salary is no more
reachable this way than it was before.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Final

from app.core.job_import_compensation import StatedPay, owns_its_line, read_pay

#: Label rows a job page prints, and the field each one settles.
#:
#: Deliberately short. Every entry here has to be a label whose meaning is the
#: same on any site — "Compensation", "Type", "Location". Anything needing
#: interpretation belongs to the model, not to this.
_LABELS: Final[tuple[tuple[str, str], ...]] = (
    ("compensation", r"(?:compensation|salary|pay|stipend|budget)"),
    ("engagement", r"(?:job\s+type|employment\s+type|type|engagement)"),
)

#: "Compensation ₹5,000 / mo" — label, then value, on one line or the next.
def _label_pattern(label: str) -> re.Pattern[str]:
    return re.compile(
        rf"^[ \t]*{label}[ \t]*[:\-–]?[ \t]*\n?[ \t]*(?P<value>[^\n]{{1,120}})$",
        re.IGNORECASE | re.MULTILINE,
    )


#: Wording that names a supported engagement. Ordered so the more specific
#: reading wins: "part-time / freelance" is freelance work at part-time volume,
#: and the freelance half is what decides how the offer is structured.
_ENGAGEMENT_WORDS: Final[tuple[tuple[str, str], ...]] = (
    ("internship", "internship"),
    ("intern", "internship"),
    ("freelance", "ongoing_freelance"),
    # Both spellings of the same idea. "fixed-term" was missing while its
    # synonym "contract" was present, so a page using the more precise word got
    # nothing — the generated matrix found the asymmetry.
    ("fixed-term", "fixed_term"),
    ("fixed term", "fixed_term"),
    ("fixed_term", "fixed_term"),
    ("contract", "fixed_term"),
    ("part-time", "part_time"),
    ("part time", "part_time"),
    ("part_time", "part_time"),
    ("full-time", "full_time"),
    ("full time", "full_time"),
    # Schema.org writes employmentType as FULL_TIME. When that value is printed
    # into visible copy rather than markup, the reader has to know it.
    ("full_time", "full_time"),
    ("retainer", "retainer"),
    ("permanent", "full_time"),
)

#: "₹5,000 / mo", "$30 per hour", "INR 40000 monthly", "Rs. 5,000 per month".
#:
#: Three families of miss were found by generating every currency × period ×
#: amount × spacing rendering rather than listing strings, and all three cost a
#: stated rate entirely — which then produced a question about pay the employer
#: had already printed:
#:
#: * ``Rs`` and ``Rs.`` were not currencies at all, though on Indian job boards
#:   they are at least as common as ``₹``. Eighty currency/period pairs.
#: * ``an`` is the article in "$40 an hour" and was not a separator, so the
#:   period never matched.
#: * ``annual`` without its ``-ly`` was not a period.
#:
#: The ``a``/``an`` separators need their word boundary. Without it ``a`` ate the
#: first letter of the period itself: "₹500000 annually" left "nnually".
_AMOUNT = re.compile(
    r"(?P<symbol>[₹$€£])?\s*(?P<currency>INR|USD|EUR|GBP|AED|SGD|Rs\.?)?\s*"
    r"(?P<amount>\d[\d,\.]*)\s*"
    r"(?:(?P<sep>/|per|an\b|a\b)\s*)?"
    r"(?P<unit>mo|month|monthly|hr|hour|hourly|yr|year|yearly|annually|annual|"
    r"annum|week|weekly|day|daily|project|video|piece|post|episode)?",
    re.IGNORECASE,
)

_SYMBOL_CURRENCY: Final[dict[str, str]] = {"₹": "INR", "$": "USD", "€": "EUR", "£": "GBP"}

#: Currency words that are not already the code the product stores.
_CURRENCY_WORDS: Final[dict[str, str]] = {"rs": "INR", "rs.": "INR"}

#: How a stated period maps onto the product's own units.
_UNITS: Final[dict[str, str]] = {
    "mo": "per month", "month": "per month", "monthly": "per month",
    "hr": "per hour", "hour": "per hour", "hourly": "per hour",
    "yr": "per year", "year": "per year", "yearly": "per year",
    "annual": "per year", "annually": "per year", "annum": "per year",
    "week": "per week", "weekly": "per week",
    "day": "per day", "daily": "per day",
    "project": "per project", "video": "per video", "piece": "per deliverable",
    "post": "per post", "episode": "per episode",
}


@dataclass(frozen=True)
class LabelledFacts:
    """What the page printed under a label, in the product's own vocabulary."""

    engagement_type: str | None = None
    budget_amount: int | None = None
    #: The upper end, when the page stated one. A page saying "up to ₹20,000"
    #: has named a ceiling and no floor, and the two are not the same fact.
    budget_max: int | None = None
    budget_currency: str | None = None
    budget_unit: str | None = None
    compensation_mode: str | None = None
    #: The exact line each value came from, for evidence.
    evidence: dict[str, str] | None = None


def _read_engagement(value: str) -> str | None:
    lowered = value.casefold()
    # "Part-time / Freelance" names two. Freelance decides how the engagement is
    # structured; part-time only describes its volume, which weekly hours carry.
    if "freelance" in lowered:
        return "ongoing_freelance"
    for word, engagement in _ENGAGEMENT_WORDS:
        if word in lowered:
            return engagement
    return None


def _apply_pay(
    stated: StatedPay,
    found: dict[str, object],
    evidence: dict[str, str],
    excerpt: str,
) -> None:
    """Record stated pay in the product's own vocabulary, without rounding it up.

    The mode is only set where the page settled it. "Up to ₹20,000" names a
    ceiling and no floor, and the product has no open-ended range — so the
    ceiling is stored and the mode is left for the recruiter, rather than
    promoting a maximum into a flat rate the employer never offered.
    """

    if stated.currency:
        found["budget_currency"] = stated.currency
    if stated.unit:
        found["budget_unit"] = stated.unit

    if stated.qualifier == "negotiable":
        # Deliberately writes nothing. "Competitive" and "DOE" tell a reader
        # there is no figure; they do not tell this product that the recruiter
        # chose its `negotiable` compensation mode, which is a publishable
        # state. A keyword match is not that decision.
        #
        # The qualifier still exists on the fact so an evidenced provider
        # reading can carry it — the restraint belongs to this detector, not to
        # the representation.
        return

    if stated.minimum is not None:
        found["budget_amount"] = stated.minimum
    if stated.maximum is not None:
        found["budget_max"] = stated.maximum

    if stated.qualifier in {"range", "minimum_only", "maximum_only"}:
        # A one-sided bound is still a range — a range with one end the page did
        # not state. Calling it "fixed" would promote a ceiling into a promise.
        found["compensation_mode"] = "range"
    elif stated.qualifier == "exact":
        # One figure is a fixed rate, not a range. Inventing a second bound
        # would advertise a spread the employer never offered.
        found["compensation_mode"] = "fixed"
    elif stated.qualifier == "approximate":
        # "around ₹20,000" is a figure its author declined to stand behind
        # exactly. It has its own native mode now, so it is no longer
        # indistinguishable from an equal-ended range or from an exact rate.
        found["compensation_mode"] = "approximate"
        found.pop("budget_max", None)

    evidence["compensation"] = excerpt


def _read_compensation(value: str) -> tuple[int, str, str] | None:
    """A single stated figure with its currency and period, or nothing.

    Superseded by :func:`app.core.job_import_compensation.read_pay`, and kept
    because the accepted grammar suite pins its behaviour directly.
    """

    match = _AMOUNT.search(value)
    if not match:
        return None
    raw = match.group("amount").replace(",", "").rstrip(".")
    if not raw.isdigit():
        return None
    amount = int(raw)
    currency = match.group("currency")
    if currency:
        # "Rs" is how a page writes rupees; "INR" is how the product stores them.
        currency = _CURRENCY_WORDS.get(currency.casefold(), currency.upper())
    else:
        symbol = match.group("symbol")
        currency = _SYMBOL_CURRENCY.get(symbol or "")
    unit = _UNITS.get((match.group("unit") or "").casefold())
    if not (currency and unit):
        # A bare number is not a rate. Guessing its period is exactly the kind
        # of invention the rest of the pipeline refuses to make.
        return None
    return amount, currency, unit


#: Where the page stops being about this job and starts advertising others.
#:
#: A generated corpus made the cost exact: on 54 of 160 composed pages the
#: reader took a neighbouring listing's rate. The pattern is obvious once seen —
#: when the job itself prints no compensation, the first "Compensation" label on
#: the page belongs to the "Similar jobs" card underneath it, and the draft then
#: advertises a different company's salary.
#:
#: Earlier tests missed it because they always gave the primary job a rate, so
#: the first match was correct by position rather than by belonging.
#: Composed rather than enumerated.
#:
#: The first version listed nine headings and 234 of 304 generated variants
#: walked straight past it — "Related roles", "Other opportunities",
#: "Vacancies", a trailing em dash, a bracketed count. Each miss let a
#: neighbouring listing's salary become this job's.
#:
#: Unlike platform names, this vocabulary really is closed: an English job page
#: introduces other jobs with a qualifier ("similar", "related", "more") and a
#: job noun ("jobs", "roles", "openings", "vacancies"). Composing the two covers
#: the space instead of guessing at points in it, and a heading nobody has seen
#: is still made of the same parts.
_OTHER_JOBS_QUALIFIER = (
    r"(?:similar|related|other|more|additional|recommended|suggested|featured|"
    r"latest|current|available|open|explore\s+more|browse|view\s+all|see\s+all|"
    r"people\s+also\s+viewed|you\s+m(?:ay|ight)\s+also\s+like|"
    r"(?:jobs?|roles?|careers?)\s+you\s+m(?:ay|ight)\s+like|"
    r"more\s+from\s+this\s+(?:company|employer)|see\s+also)"
)

_OTHER_JOBS_NOUN = (
    r"(?:jobs?|roles?|openings?|positions?|opportunities|opportunity|vacancies|"
    r"vacancy|careers?|listings?|posts?)"
)

_OTHER_JOBS_BOUNDARY = re.compile(
    r"^[ \t]*[-—–*•]?[ \t]*"
    # Either "<qualifier> <noun>", or a qualifier that already contains its own
    # noun ("people also viewed", "see also", "you may also like").
    # Qualifiers stack: "More related roles" is two of them before the noun.
    rf"(?:{_OTHER_JOBS_QUALIFIER}(?:[ \t]+{_OTHER_JOBS_QUALIFIER})?"
    rf"(?:[ \t]+(?:for[ \t]+you|to[ \t]+you))?"
    rf"(?:[ \t]+{_OTHER_JOBS_NOUN})?"
    rf"|{_OTHER_JOBS_NOUN}[ \t]+you[ \t]+m(?:ay|ight)[ \t]+like"
    # A bare noun, but only the ones that exist to introduce a list. "Roles"
    # and "Jobs" alone are excluded: a posting can head its own section that
    # way, and cutting the page there would lose the job's own facts.
    rf"|(?:vacancies|vacancy|openings|opportunities))"
    # A count, a colon, a dash, an arrow — whatever the page decorates it with.
    r"[ \t]*(?:\(\s*\d+\s*\)|\[\s*\d+\s*\]|\d+)?"
    r"[ \t]*[:：\-—–>»]*[ \t]*$",
    re.IGNORECASE | re.MULTILINE,
)


#: Headings that begin a posting's own long-form body.
#:
#: A page states its own labelled facts near the top — beside the title, above
#: the prose. A recommendation card sits *below* the body, and on a great many
#: sites it carries no heading at all: just a title, a salary and a location,
#: repeated. Half of a thousand generated heading-free layouts contaminated the
#: draft that way, so the boundary cannot depend on a heading existing.
_BODY_SECTION = re.compile(
    r"^[ \t]*(?:about(?:\s+(?:the|this)\s+(?:role|job|position|company|us))?|"
    r"the\s+role|role\s+overview|job\s+description|overview|summary|"
    r"responsibilities|key\s+responsibilities|what\s+you'?ll\s+do|"
    r"what\s+you\s+will\s+do|requirements?|qualifications?|who\s+you\s+are|"
    r"your\s+profile|skills|benefits|perks|what\s+we\s+offer|how\s+to\s+apply)"
    r"[ \t]*:?[ \t]*$",
    re.IGNORECASE | re.MULTILINE,
)

#: A labelled row of the kind a job card repeats.
_LABELLED_ROW = re.compile(
    r"^[ \t]*(?:compensation|salary|pay|stipend|budget|job\s+type|employment\s+type|"
    r"type|engagement|location)[ \t]*[:\-–]",
    re.IGNORECASE | re.MULTILINE,
)


def _first_neighbour_card(text: str) -> int | None:
    """Where a second job's card begins, when no heading announces it.

    The rule is positional because the page's structure is: title, labelled
    facts, body, then other people's jobs. A labelled row appearing *after* the
    body has started belongs to something the page moved on to — unless the
    posting never had a body at all, in which case there is nothing to be after.
    """

    lines = text.splitlines(keepends=True)
    offsets: list[int] = []
    position = 0
    for line in lines:
        offsets.append(position)
        position += len(line)

    # Where the page stops being a header and starts being a description.
    #
    # A recognised body heading is the clearest marker, but requiring one made
    # the whole structural rule collapse whenever a page used wording nobody had
    # listed — "Your creative mandate", "Day to day", "What success looks like".
    # 437 of 1,500 generated layouts took a neighbour's salary that way, with
    # the heading list fully intact.
    #
    # Prose works as well and needs no vocabulary: a sentence is where the
    # header ends, whatever the heading above it was called.
    body = _BODY_SECTION.search(text)
    prose = _PROSE_LINE.search(text)
    starts = [match.end() for match in (body, prose) if match is not None]
    if not starts:
        return None

    for row in _LABELLED_ROW.finditer(text, min(starts)):
        index = max(
            (i for i, start in enumerate(offsets) if start <= row.start()),
            default=0,
        )
        # A card announces itself with its own title and employer: two short
        # lines that are neither prose nor a section heading. A posting stating
        # its own pay below its body is preceded by prose instead, and cutting
        # there would lose a fact the employer did state — which an earlier
        # version of this did.
        preceding = [line.strip() for line in lines[max(0, index - 2) : index]]
        preceding = [line for line in preceding if line]
        if len(preceding) < 2:
            continue
        if all(_looks_like_a_card_line(line) for line in preceding):
            return offsets[max(0, index - len(preceding))]
    return None


#: A line that reads as a sentence rather than a heading or a labelled row.
#:
#: The end of the header region. Deliberately crude — it only has to separate
#: "Content Creator / Larkfield Studio / Compensation: …" from the description
#: underneath, and any sentence does that.
_PROSE_LINE = re.compile(r"^[ \t]*\S[^\n]{25,}[.!?][ \t]*$", re.MULTILINE)


def _looks_like_a_card_line(line: str) -> bool:
    """Whether a line reads as a job card's title or employer rather than prose.

    Short, no sentence punctuation, not a bullet, not itself a labelled row.
    """

    if not line or len(line) > 70:
        return False
    if line.endswith((".", "!", "?", ":", ";", ",")):
        return False
    if line.lstrip().startswith(("-", "*", "•", "–")):
        return False
    if _LABELLED_ROW.match(line) or _BODY_SECTION.match(line):
        return False
    return len(line.split()) <= 8


def primary_job_text(normalized_text: str | None) -> str:
    """The part of a page that is about the job it is a page for.

    Everything from a "Similar jobs" heading onward belongs to other listings.
    Reading labels out of it attributes another employer's facts to this one.
    """

    text = normalized_text or ""
    cuts = [match.start() for match in [_OTHER_JOBS_BOUNDARY.search(text)] if match]
    structural = _first_neighbour_card(text)
    if structural is not None:
        cuts.append(structural)
    return text[: min(cuts)] if cuts else text


def labelled_facts(normalized_text: str | None) -> LabelledFacts:
    """Read the handful of facts a page states plainly under a label."""

    text = primary_job_text(normalized_text)
    if not text.strip():
        return LabelledFacts()

    found: dict[str, object] = {}
    evidence: dict[str, str] = {}

    for name, label in _LABELS:
        match = _label_pattern(label).search(text)
        if not match:
            continue
        value = match.group("value").strip()
        if not value:
            continue

        if name == "engagement":
            engagement = _read_engagement(value)
            if engagement:
                found["engagement_type"] = engagement
                evidence["engagement_type"] = value
        elif name == "compensation":
            stated = read_pay(value)
            if stated:
                _apply_pay(stated, found, evidence, value)

    if "budget_amount" not in found and "budget_max" not in found:
        # No label carried the pay. Most boards print it as a bare line —
        # "Up to ₹20,000 a month" — which is how the reported listing was
        # missed entirely, and the label reader had no way to see it.
        #
        # A line at a time, and only when the money *owns* the line. A figure
        # inside a sentence is regularly not the offer: "Previous salary of
        # ₹30,000 per month will be verified" carries a currency and a period
        # and is somebody else's number.
        for line in text.splitlines():
            if not line.strip():
                continue
            stated = read_pay(line)
            if stated and owns_its_line(line, stated):
                _apply_pay(stated, found, evidence, line.strip())
                break

    return LabelledFacts(
        engagement_type=found.get("engagement_type"),  # type: ignore[arg-type]
        budget_amount=found.get("budget_amount"),  # type: ignore[arg-type]
        budget_max=found.get("budget_max"),  # type: ignore[arg-type]
        budget_currency=found.get("budget_currency"),  # type: ignore[arg-type]
        budget_unit=found.get("budget_unit"),  # type: ignore[arg-type]
        compensation_mode=found.get("compensation_mode"),  # type: ignore[arg-type]
        evidence=evidence or None,
    )
